import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'rw';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        'nav.home': 'Home',
        'nav.about': 'What We Do',
        'nav.about_page': 'About',
        'nav.how_we_work': 'How We Work',
        'nav.impact': 'Impact & Stories',
        'nav.resources': 'Resources',
        'nav.contact': 'Contact',
        'nav.menu': 'Menu',
        'nav.donate': 'Donate Now',
        'nav.dashboard': 'Dashboard',
        'nav.profile': 'My Profile',
        'nav.logout': 'Logout',
        'nav.login': 'Login',
        'nav.strategic_direction': 'Strategic Direction',
        'navbar.mega.donate_title': 'Donate today',
        'navbar.mega.donate_desc': 'Give your support where it\'s needed most to empower girls and women.',
        'navbar.mega.donate_btn': 'Donate now',
        'navbar.mega.who_we_are': 'Who We Are',
        'navbar.mega.our_strategy': 'Our Strategy',
        'navbar.mega.strategic_direction': 'Strategic Direction',
        'navbar.mega.knowledge_hub': 'Knowledge Hub',
        'navbar.mega.report_title': 'Read our 2024 annual report',
        'navbar.mega.report_desc': 'LCEO\'s objectives, activities and achievements in 2024 can be found in our core report.',
        'navbar.mega.report_btn': 'Read the report',
        'navbar.mega.real_impact': 'Real Impact',
        'navbar.mega.help_support': 'Help & Support',
        'navbar.mega.help_faq': 'Help & FAQ',
        'navbar.mega.join_mission_title': 'Join our mission',
        'navbar.mega.join_mission_desc': 'Become a champion for change and help us transform more lives together.',
        'navbar.mega.get_involved_btn': 'Get involved',
        'navbar.mega.get_in_touch': 'Get in Touch',
        'navbar.mega.support_lceo': 'Support LCEO',
        'navbar.user.role': 'Role',
        'donation.trusted_platform': '#1 Trusted Impact Platform',
        'donation.starts_here_title': 'Successful impact starts here',
        'donation.btn_start': 'Start Donating',
        'donation.stats_title': 'More than $5M raised every year on LCEO.*',
        'donation.stats_desc': 'Get started in just a few minutes — with helpful options to pick the perfect cause and share it with the world.',
        'donation.make_donation': 'Make a Donation',
        'donation.secure_msg': 'Your gift is secure and tax-deductible.',
        'donation.select_amount': 'Select Amount (USD)',
        'donation.custom_amount': 'Custom Amount',
        'donation.name_placeholder': 'Your Name',
        'donation.email_placeholder': 'Email Address',
        'donation.message_placeholder': 'Message of encouragement (Optional)',
        'donation.btn_donate_now': 'Donate ${{amount}} Now',
        'donation.securing_payment': 'Securing Payment...',
        'donation.advanced_options': 'Advanced Options: Select Programs & Recurring Gifts',
        'donation.impact_circle_title': 'Join the Impact Circle',
        'donation.impact_circle_desc': 'Every dollar transforms a life in the Bugesera District of Rwanda.',
        'donation.step_n_of_m': 'Step {{step}} of {{total}}',
        'donation.complete_percent': '{{percent}}% Complete',
        'donation.direct_impact_title': 'Direct Your Impact',
        'donation.direct_impact_desc': 'Choose a specific area to support or donate where it\'s needed most.',
        'donation.where_needed_most': 'Where Needed Most',
        'donation.where_needed_most_desc': 'Allow LCEO to direct your gift to areas of highest priority.',
        'donation.switch_quick': 'Switch back to quick donation',
        'donation.continue': 'Continue',
        'donation.gift_choice_title': 'Gift Choice',
        'donation.gift_choice_desc': 'Sustain our mission with a monthly gift or make a one-time contribution.',
        'donation.monthly_giving': 'Monthly Giving',
        'donation.one_time_gift': 'One-Time Gift',
        'donation.other_amount': 'Enter other amount',
        'donation.back': 'Back',
        'donation.about_you_title': 'About You',
        'donation.about_you_desc': 'Help us keep you updated on the impact of your gift.',
        'donation.full_name': 'Full Name',
        'donation.email_address': 'Email Address',
        'donation.message_support': 'Message of Support (Optional)',
        'donation.message_community_placeholder': 'Your message to the girls and community...',
        'donation.show_anonymous': 'Show my donation as "Anonymous" on public feeds',
        'donation.payment_method_title': 'Payment Method',
        'donation.payment_method_desc': 'Select your preferred way to support our mission.',
        'donation.review_donation': 'Review Donation',
        'donation.review_summary_title': 'Review Summary',
        'donation.review_summary_desc': 'Please verify your donation details below.',
        'donation.program_label': 'Program',
        'donation.frequency_label': 'Frequency',
        'donation.donor_label': 'Donor',
        'donation.payment_label': 'Payment',
        'donation.total_amount_label': 'Total Amount',
        'donation.terms_privacy': 'By clicking "Complete Donation", you agree to our Terms of Service and Privacy Policy. Your payment information is processed securely.',
        'donation.btn_complete': 'Complete Donation',
        'donation.processing': 'Processing...',
        'donation.anonymous': 'Anonymous',
        'donation.public': 'Public',
        'donation.payment_method': 'Payment Method',
        'donation.payment_method_card': 'Credit / Debit Card',
        'donation.payment_method_card_subtitle': 'Visa, Mastercard, Amex',
        'donation.payment_method_mobile': 'Mobile Money',
        'donation.payment_method_mobile_subtitle': 'MTN, Airtel/Tigo Money',
        'donation.payment_method_bank': 'Bank Transfer',
        'donation.payment_method_bank_subtitle': 'Direct Wire / EFT',
        'donation.payment_method_paypal': 'PayPal',
        'donation.payment_method_paypal_subtitle': 'Fast and secure',
        'donation.program.education_name': 'Education Support',
        'donation.program.education_desc': 'Help girls stay in school with scholarships and supplies.',
        'donation.program.medical_name': 'Medical Care',
        'donation.program.medical_desc': 'Provide health education and hygiene kits to communities.',
        'donation.program.business_name': 'Business Incubation',
        'donation.program.business_desc': 'Support women entrepreneurs with seed funding and mentorship.',
        'donation.program.emergency_name': 'Emergency Response',
        'donation.program.emergency_desc': 'Provide rapid support to families in crisis situations.',
        'donation.program.shelter_name': 'Shelter & Safety',
        'donation.program.shelter_desc': 'Ensure vulnerable women have a safe place to live.',
        'donation.success_title': 'Thank You for Your Generosity!',
        'donation.success_subtitle': 'Your contribution is a vital step toward protecting the dignity and rights of women and girls in Rwanda.',
        'donation.donor_name': 'Donor Name',
        'donation.donation_amount': 'Donation Amount',
        'donation.transaction_id': 'Transaction ID',
        'donation.date': 'Date',
        'donation.next_steps_title': 'What Happens Next?',
        'donation.next_steps_1': 'You will receive an email confirmation with your donation receipt shortly.',
        'donation.next_steps_2': 'Our team will begin allocating these funds to your chosen program immediately.',
        'donation.next_steps_3': 'Stay tuned for impact updates and stories from the communities you are supporting.',
        'donation.back_home': 'BACK TO HOMEPAGE',
        'impact.education_support_short': 'School supplies for 3 girls',
        'impact.skills_training_short': 'IkiraroBiz Skills training',
        'impact.starter_kit_short': 'Micro-business starter kit',
        'impact.shelter_safety_short': 'One year of shelter & safety',
        'hero.title': 'Protecting the Dignity and Rights of Women and Girls',
        'hero.subtitle': 'We support girls, caregivers, and youth by promoting education, health, mentorship, and skills development.',
        'mission.badge': 'Our Mission',
        'mission.title': 'Protecting the Dignity and Rights of Women and Girls.',
        'mission.desc': 'Whether through education scholarships, business seed funding, or mental health support, we deliver the comprehensive care needed to transform lives. From grassroots community engagement to systemic advocacy, we help vulnerable women and girls convert challenges into measurable impact, strengthen resilience, and accelerate their journey to independence in Bugesera and beyond.',
        'mission.empowerment': 'Economic Empowerment',
        'mission.education': 'Education Access',
        'mission.health': 'Mental Health Support',
        'mission.advocacy': 'Community Advocacy',
        'mission.learn_more': 'Learn More About Us',
        'impact.heading': 'Impact by the Numbers',
        'impact.women': 'Women & girls reached & empowered',
        'impact.education': 'Girls stayed in school through our support',
        'impact.livelihoods': 'Businesses launched and thriving',
        'impact.leadership': 'Change Champions trained as leaders',
        'programs.subheading': 'Our Programs',
        'programs.heading': 'Targeted Interventions',
        'programs.desc': 'We focus on key areas that create lasting change for women and their families.',
        'programs.view_all': 'VIEW ALL OUR PROGRAMS',
        'stories.subheading': 'Impact Stories',
        'stories.heading': 'Stories of Change',
        'stories.desc': 'Witness the profound transformation in the lives of those we serve.',
        'gallery.heading': 'Photo Gallery',
        'footer.stay_connected': 'Stay Connected',
        'footer.newsletter_desc': 'Subscribe to our newsletter for updates, impact stories, and ways to get involved',
        'footer.email_placeholder': 'Enter your email',
        'footer.subscribe': 'Subscribe',
        'footer.brand_desc': 'Empowering vulnerable young women and girls in Rwanda through education, entrepreneurship, and health programs.',
        'footer.quick_links': 'Quick Links',
        'footer.get_involved': 'Get Involved',
        'footer.contact_us': 'Contact Us',
        'footer.address_label': 'Address',
        'footer.phone_label': 'Phone',
        'footer.email_label': 'Email',
        'footer.copyright': 'All rights reserved.',
        'footer.monthly_giving': 'Monthly Giving',
        'footer.volunteer': 'Volunteer',
        'footer.partner_with_us': 'Partner With Us',
        'btn.learn_more': 'Learn More',
        'btn.donate': 'Donate',
        'home.impact_heading': 'Our Impact Story in Bugesera District',
        'home.impact_women': 'Women & girls reached & empowered',
        'home.impact_education': 'Girls stayed in school through our support',
        'home.impact_livelihoods': 'Businesses launched and thriving',
        'home.impact_leadership': 'Change Champions trained as leaders',
        'home.mission_badge': 'Our Mission',
        'home.mission_title': 'Protecting the Dignity and Rights of Women and Girls',
        'home.mission_desc': 'Whether through education scholarships, business seed funding, or mental health support, we deliver the comprehensive care needed to transform lives.',
        'home.mission_empowerment': 'Economic Empowerment',
        'home.mission_education': 'Education Access',
        'home.mission_health': 'Mental Health Support',
        'home.mission_advocacy': 'Community Advocacy',
        'home.mission_learn_more': 'Learn More About Us',
        'home.impact_areas_badge': 'OUR CORE IMPACT AREAS',
        'home.programs_view_all': 'VIEW ALL OUR PROGRAMS',
        'home.impact_areas_title': 'Integrated Development Strategy',
        'home.impact_areas_emergency_title': 'Emergency Response',
        'home.impact_areas_emergency_desc': 'Providing immediate humanitarian support and protective services for families in crisis.',
        'home.impact_areas_economic_title': 'Economic Empowerment',
        'home.impact_areas_economic_desc': 'Building resilient futures through financial literacy, entrepreneurship, and market access.',
        'home.impact_areas_srhr_title': 'SRHR & Menstrual Health',
        'home.impact_areas_srhr_desc': 'Dignity through menstrual hygiene support and reproductive health education for schoolgirls.',
        'home.impact_areas_education_title': 'Education & School Retention',
        'home.impact_areas_education_desc': 'Ensuring every girl stays in school through scholarships and academic performance monitoring.',
        'home.impact_areas_gender_title': 'Gender & Protection',
        'home.impact_areas_gender_desc': 'Fighting gender-based violence and promoting equal rights for women within their communities.',
        'home.impact_areas_human_title': 'Human Capital & Resilience',
        'home.impact_areas_human_desc': 'Developing leadership skills and psychological resilience in young women across Rwanda.',
        'home.stories_journey_suffix': " invested in her community's future and growth",
        'home.stories_read_more': 'READ MORE STORIES',
        'home.partners_heading': 'Trusted global partners working together with LCEO every day.',
        'home.partner_fawe_subtitle': 'FORUM FOR AFRICAN WOMEN EDUCATIONALISTS',
        'home.partner_ecorys_subtitle': 'INTERNATIONAL DEVELOPMENT CONSULTANCY',
        'home.partner_mor_subtitle': 'STRATEGIC PARTNERSHIP & DEVELOPMENT',
        'home.impact_circle_badge': 'Support Sustainable Change',
        'home.impact_circle_title': 'Join Our Impact Circle',
        'home.impact_circle_desc': 'Your monthly support provides sustained transformation for vulnerable young women and girls in Rwanda.',
        'home.impact_circle_tier1_price': '$25/mo',
        'home.impact_circle_tier1_desc': 'Supports menstrual hygiene for 5 girls every month, ensuring they never miss school.',
        'home.impact_circle_btn': 'JOIN CIRCLE',
        'home.impact_circle_tier2_price': '$50/mo',
        'home.impact_circle_tier2_desc': 'Covers school fees and essential supplies for one girl, securing her education.',
        'home.impact_circle_btn_alt': 'JOIN NOW',
        'home.impact_circle_tier3_price': '$100/mo',
        'home.impact_circle_tier3_desc': 'Provides seed capital and mentorship for one entrepreneur to launch her business.',
        'home.sdg_title': 'Empowering Lives + Strengthening Communities Through Global Goals',
        'home.sdg_desc1': 'At LCEO, we believe that sustainable development is only possible when we align our grassroots efforts with global standards. By focusing on these key Sustainable Development Goals, we ensure that every scholarship, business grant, and mental health session contributes to a larger vision of dignity and equality for all Rwandans.',
        'home.sdg_desc2': 'Our integrated approach in Bugesera District directly impacts thousands of lives, bridging the gap between local challenges and international aspirations for social justice and economic resilience.',
        'home.sdg_report_btn': 'View Our Impact Report →',
        'home.sdg_goal_label': 'Goal',
        'home.movement_badge': 'Join The Movement',
        'home.movement_title': 'Be Part of the Transformation',
        'home.movement_desc': 'Whether you give your time or your resources, you are investing in a future where every girl can thrive. Choose your path to impact.',
        'home.movement_donor_title': 'Financial Donor',
        'home.movement_donor_desc': 'Support our mission through one-time or recurring financial gifts that directly fund scholarships and business grants.',
        'home.movement_volunteer_title': 'Skilled Volunteer',
        'home.movement_volunteer_desc': 'Share your expertise in healthcare, education, or business to provide high-quality mentorship and training.',
        'home.movement_partner_title': 'Strategic Partner',
        'home.movement_partner_desc': 'Join forces with LCEO to scale our integrated empowerment model across new sectors and communities.',
        'home.movement_advocacy_title': 'Community Advocate',
        'home.movement_advocacy_desc': 'Raise awareness and champion the rights of girls and women in the Bugesera region within your local network.',
        'home.movement_form_badge': 'Join Us Now',
        'home.movement_form_title': 'Become A Volunteer',
        'home.movement_name_placeholder': 'Your Name',
        'home.movement_email_placeholder': 'Your Email',
        'home.movement_phone_placeholder': 'Phone No',
        'home.movement_location_placeholder': 'Location',
        'home.movement_message_placeholder': 'Your Message',
        'home.movement_btn': 'Become A Volunteer',
        'home.sdg_goal1': 'No Poverty',
        'home.sdg_goal3': 'Good Health',
        'home.sdg_goal4': 'Quality Education',
        'home.sdg_goal5': 'Gender Equality',
        'home.sdg_goal8': 'Decent Work',
        'home.sdg_goal10': 'Reduced Inequality',
        'programs.p1.title': 'Education Retention',
        'programs.p1.description': 'Addressing barriers to education for vulnerable girls through comprehensive support systems.',
        'programs.p1.subtitle': 'Academic Excellence',
        'programs.p1.features_title': 'Key Highlights:',
        'programs.p1.feature1': 'Full tuition scholarships',
        'programs.p1.feature2': 'School supplies and uniforms',
        'programs.p1.feature3': 'Mentorship and tutoring',
        'programs.p1.feature4': 'Parental engagement',
        'programs.p1.status': 'Active in Bugesera',
        'programs.p2.title': 'Economic Empowerment',
        'programs.p2.description': 'Empowering women entrepreneurs with the tools and capital to build sustainable businesses.',
        'programs.p2.subtitle': 'Livelihood Support',
        'programs.p2.features_title': 'Program Pillars:',
        'programs.p2.feature1': 'Seed funding grants',
        'programs.p2.feature2': 'Business skills training',
        'programs.p2.feature3': 'Market linkage access',
        'programs.p2.feature4': 'Savings group formation',
        'programs.p2.status': '150+ Businesses Funded',
        'programs.p3.title': 'Holistic Health Support',
        'programs.p3.description': 'Integrating mental health and reproductive wellness into the core of community development.',
        'programs.p3.subtitle': 'Well-being & Dignity',
        'programs.p3.features_title': 'Services Provided:',
        'programs.p3.feature1': 'Menstrual hygiene kits',
        'programs.p3.feature2': 'Individual counseling',
        'programs.p3.feature3': 'Health education workshops',
        'programs.p3.feature4': 'SRHR awareness training',
        'programs.p3.status': 'Expanding Reach',
        'about.title': 'About LCEO',
        'about.breadcrumb_home': 'Home',
        'about.breadcrumb_about': 'About',
        'about.team_caption_title': 'Education, Entrepreneurship, and Mentorship',
        'about.team_caption_subtitle': 'Delivered by a Dedicated Team',
        'about.badge': 'About Us',
        'about.title_impact_prefix': 'Building Long-Term Impact for ',
        'about.title_impact_highlight': 'Vulnerable Communities',
        'about.description': 'Life-Changing Endeavor Organization (LCEO) is a Kigali-based non-profit delivering education, health, and economic empowerment services under one integrated team. Trusted by communities across Rwanda, we build sustainable systems and growth-driven initiatives that generate real human results.',
        'about.vision_tab': 'Our Vision',
        'about.mission_tab': 'Our Mission',
        'about.vision_desc': 'A society where young women and girls are mentally strong, educated, and economically empowered — free to lead and thrive in their communities.',
        'about.mission_desc': 'To walk alongside girls and women as they heal, grow, and thrive — through mindset shift, mental resilience, quality education, and sustainable economic empowerment.',
        'about.foundation_badge': 'Our Foundation',
        'about.values_title': 'Our Core Values',
        'about.values_heading_prefix': 'Guided by Purpose, Driven by ',
        'about.values_heading_highlight': 'Impact',
        'about.values_desc': 'The principles that guide our work and commitment to empowering vulnerable young women and girls in Rwanda.',
        'about.value_empowerment_title': 'Empowerment',
        'about.value_empowerment_desc': 'Unlocking the inherent potential in every girl to lead.',
        'about.value_protection_title': 'Protection',
        'about.value_protection_desc': 'Creating safe, nurturing spaces for healing and growth.',
        'about.value_innovation_title': 'Innovation',
        'about.value_innovation_desc': 'Using evidence-based and creative approaches for change.',
        'about.value_compassion_title': 'Compassion',
        'about.value_compassion_desc': 'Walking alongside our beneficiaries with empathy and respect.',
        'about.value_community_title': 'Community',
        'about.value_community_desc': 'Building sustainable networks of local and global support.',
        'about.value_excellence_title': 'Excellence',
        'about.value_excellence_desc': 'Committed to delivering measurable and lasting human results.',
        'about.value_card_badge': 'Core Principle',
        'about.value_card_footer': 'LCEO Support',
        'about.read_more_btn': 'READ MORE',
        'about.journey_btn': 'Be Part of Our Journey',
        'about.team_badge': 'Meet Our Team',
        'about.team_title': 'The People Behind LCEO',
        'about.team_role_sarah': 'Executive Director',
        'about.team_bio_sarah': '15+ years of experience in development and empowerment work in Rwanda.',
        'about.team_role_jean': 'Program Manager',
        'about.team_bio_jean': 'Expert in education and youth development programs across local communities.',
        'about.team_role_grace': 'Finance Director',
        'about.team_bio_grace': 'Ensuring transparency, accountability, and sustainable financial operations.',
        'about.team_role_emmanuel': 'M&E Specialist',
        'about.team_bio_emmanuel': 'Data-driven approach to measuring and improving program effectiveness.',
        'about.progress_badge': 'Progress',
        'about.progress_title': 'Milestones & Achievements',
        'about.milestone_2020_title': 'LCEO Founded',
        'about.milestone_2020_desc': 'Established in Bugesera District with a vision to transform lives through mindset and mental resilience.',
        'about.milestone_2021_title': 'First Program Launch',
        'about.milestone_2021_desc': 'The Girls School Retention program reaches its first 50 beneficiaries with integrated support.',
        'about.milestone_2022_title': 'IkiraroBiz Initiative',
        'about.milestone_2022_desc': 'A major entrepreneurship shift, supporting 30 young women in launching sustainable businesses.',
        'about.milestone_2023_title': 'Major Expansion',
        'about.milestone_2023_desc': 'Scaled operations to multiple districts, reaching 200+ beneficiaries across all core pillars.',
        'about.milestone_2024_title': 'Recognition & Growth',
        'about.milestone_2024_desc': 'Signed strategic partnership with FAWE Rwanda, now serving 312 beneficiaries and counting.',
        'about.image_impact_label': 'Impact 2023',
        'about.image_journey_label': 'Our Journey',
        'about.legacy_label': 'Legacy',
        'work.breadcrumb_home': 'Home',
        'work.breadcrumb_work': 'How We Work',
        'work.title': 'How We Work',
        'work.more_ways_title': 'More ways to support LCEO',
        'work.support_will': 'Leave a gift in your will',
        'work.support_regular': 'Make a regular donation',
        'work.support_fundraise': 'Fundraise for LCEO',
        'work.support_corporate': 'Become a corporate supporter',
        'work.story_badge': 'Story',
        'work.featured_story_title': 'Our mission to protect and empower, explained',
        'work.featured_story_desc': 'Updated for 2026: Discover the five core pillars driving our community-led transformation and how we\'re scaling our impact across the region.',
        'work.secondary_story_title': 'Impact of integrated mentorship',
        'work.secondary_story_desc': 'Community leaders describe how our integrated approach is creating lasting change in local villages.',
        'work.impact_badge': 'Our Impact Areas',
        'work.impact_title': 'Areas of Intervention',
        'work.impact_desc': 'LCEO operates across multiple strategic areas to create a protective and empowering environment.',
        'work.area_edu_title': 'Education & Retention',
        'work.area_edu_desc': 'Ensuring every girl has the resources and support to stay in school through community-led initiatives.',
        'work.area_srhr_title': 'SRHR & Dignity',
        'work.area_srhr_desc': 'Providing integrated knowledge and supplies for sexual reproductive health and dignity during menstruation.',
        'work.area_gender_title': 'Gender & Protection',
        'work.area_gender_desc': 'Advocating for rights and protecting girls from abuse and early pregnancy through legal aid systems.',
        'work.area_econ_title': 'Economic Empowerment',
        'work.area_econ_desc': 'Building livelihoods for young women through targeted skills training and market accessibility.',
        'work.area_resilience_title': 'Individual Resilience',
        'work.area_resilience_desc': 'Focusing on mental health and leadership through structured mentorship and mindset workshops.',
        'work.area_emergency_title': 'Emergency Response',
        'work.area_emergency_desc': 'Providing rapid support to girls and women in crisis situations through a dedicated rapid response team.',
        'work.methodology_badge': 'Our Methodology',
        'work.methodology_title': 'The LCEO Process',
        'work.methodology_desc': 'The Rugero Rwiza Community Change Model (RR-CCM) is our signature framework, engineered to move communities from vulnerability to complete self-reliance through a disciplined, phased approach.',
        'work.engine_title': 'A Systemic Engine for Social Change.',
        'work.engine_desc': 'Our methodology is not just a set of activities; it\'s a strategic engine designed to break the cycles of generational poverty and gender-based inequality at their source.',
        'work.engine_quote': 'Sustainable change only happens when the community takes ownership of the solution.',
        'work.certified_badge': 'Certified Methodology',
        'work.process_step1_title': 'Discovery Phase',
        'work.process_step1_desc': 'Long-term community immersion to understand cultural nuances and identify grassroots leadership potential.',
        'work.process_step2_title': 'Holistic Insight',
        'work.process_step2_desc': 'Using multi-dimensional data to map the intersectional needs of education, health, and economic stability.',
        'work.process_step3_title': 'Collaborative Co-Design',
        'work.process_step3_desc': 'Developing solutions alongside the community to ensure high adoption rates and local cultural alignment.',
        'work.process_step4_title': 'Multi-Sector Execution',
        'work.process_step4_desc': 'Deploying high-impact interventions across multiple sectors simultaneously for maximum leverage.',
        'work.process_step5_title': 'Dynamic Monitoring',
        'work.process_step5_desc': 'Continuous feedback loops and impact measurement to refine strategies in real-time.',
        'work.process_step6_title': 'Phased Sustainability',
        'work.process_step6_desc': 'Systematic hand-over to trained community leaders to ensure the model survives beyond LCEO’s direct involvement.',
        'work.framework_title': 'Detailed Strategic Framework',
        'work.framework_desc': 'Our process broken down into major operational phases.',
        'work.download_btn': 'Download PDF Guide',
        'work.phase1_title': 'Phase I: Foundation',
        'work.phase1_desc': 'Focuses on trust-building, legal frameworks, and community entry. We establish the Rugero Rwiza Hubs as centers of change and recruit local mentors.',
        'work.phase2_title': 'Phase II: Transformation',
        'work.phase2_desc': 'The core implementation peak where scholarship, mental health training, and mentorship programs run daily at maximum capacity.',
        'work.phase3_title': 'Phase III: Sustainability',
        'work.phase3_desc': 'Final transition phase focusing on local governance, cooperative formation, and building independent market links for beneficiaries.',
        'work.principles_title': 'Core Principles of Engagement',
        'work.principles_desc': 'The values that guide every step of our operational journey.',
        'work.principle1_title': 'Community Ownership',
        'work.principle1_desc': 'We don’t believe in "saving" communities. We believe in empowering them to lead their own change from within.',
        'work.principle2_title': 'Intersectional Focus',
        'work.principle2_desc': 'We address the interconnected barriers of gender, poverty, and geography to ensure no girl is left behind.',
        'work.principle3_title': 'Evidence-Driven',
        'work.principle3_desc': 'Every program is backed by rigorous data and real-world results, ensuring high-impact delivery.',
        'work.principle4_title': 'Radical Transparency',
        'work.principle4_desc': 'We maintain complete accountability to our beneficiaries, partners, and the global community.',
        'work.results_title': 'Methodology in Action: Key Results',
        'work.results_desc': 'The Rugero Rwiza Community Change Model is yielding measurable, life-altering results across our regions of operation.',
        'work.stat1_label': 'Girls Empowered',
        'work.stat1_desc': 'Direct beneficiaries of our integrated education and mental health support.',
        'work.stat2_label': 'Rugero Rwiza Hubs',
        'work.stat2_desc': 'Community-led centers acting as safe spaces for learning and mentorship.',
        'work.stat3_label': 'School Retention',
        'work.stat3_desc': 'Of our scholarship recipients remain in school through graduation.',
        'work.stat4_label': 'Local Mentors',
        'work.stat4_desc': 'Trained community leaders sustaining the model at the grassroots level.',
        'work.sdg_title': 'Aligned SDG Goals',
        'work.sdg_desc': 'LCEO contributes to the UN Sustainable Development Goals.',
        'work.sdg1': 'SDG 1: No Poverty',
        'work.sdg3': 'SDG 3: Good Health',
        'work.sdg4': 'SDG 4: Quality Education',
        'work.sdg5': 'SDG 5: Gender Equality',
        'work.sdg8': 'SDG 8: Decent Work',
        'work.sdg10': 'SDG 10: Reduced Inequalities',
        'impact_page.breadcrumb_home': 'Home',
        'impact_page.breadcrumb_impact': 'Impact & Stories',
        'impact_page.title': 'Transforming Lives, Building Futures',
        'impact_page.subtitle': 'Every statistic represents a life changed. Every number tells a story of resilience, growth, and empowerment.',
        'impact_page.badge_lceo': 'About LCEO',
        'impact_page.heading': 'Together, We Make A Difference!',
        'impact_page.description': 'Every statistic represents a life changed. See the real impact of LCEO\'s work across education, entrepreneurship, and empowerment. We believe in building sustainable futures for every girl in Rwanda.',
        'impact_page.btn_donate': 'Make A Impactful Donation',
        'impact_page.donate_now_heading': 'Donate now',
        'impact_page.exit_site_btn': 'Exit Site',
        'impact_page.sdg_badge': 'Global Agenda',
        'impact_page.sdg_title': 'Aligned with Global Goals',
        'impact_page.sdg_desc': 'LCEO’s programs contribute directly to the 2030 Agenda for Sustainable Development in Rwanda.',
        'impact_page.resilience_title': 'Community Resilience',
        'impact_page.resilience_desc': 'Building health, education, and basic stability for the most vulnerable families in Rwanda.',
        'impact_page.transformation_title': 'Societal Transformation',
        'impact_page.transformation_desc': 'Driving long-term gender equality and structural reduction of systemic inequalities through advocacy.',
        'impact_page.report_btn': 'View Detailed Report',
        'impact_page.partner_btn': 'Partner With Our Mission',
        'impact_page.outcomes_title': 'Strategic Outcomes',
        'impact_page.outcome_item1': 'Bridging tech gaps',
        'impact_page.outcome_item2': 'Economic loops',
        'impact_page.outcome_item3': 'Community advocacy',
        'impact_page.outcome_item4': 'Policy integration',
        'impact_page.outcome_item5': 'Retention models',
        'impact_page.outcome_item6': 'Resilience hubs',
        'impact_page.tab_one_off': 'One-off Impact',
        'impact_page.tab_monthly': 'Monthly Change',
        'impact_page.explore_btn': 'Explore more impact stories today',
        'impact_page.stat_one_off_1_amount': '5,000+',
        'impact_page.stat_one_off_1_desc': 'Young women reached and mentored through our core education and community programs.',
        'impact_page.stat_one_off_2_amount': '1,200+',
        'impact_page.stat_one_off_2_desc': 'Girls facilitated with protection systems to ensure they stay safely in school.',
        'impact_page.stat_one_off_3_amount': '300+',
        'impact_page.stat_one_off_3_desc': 'Champions trained to lead mindset shift initiatives within their own communities.',
        'impact_page.stat_monthly_1_amount': '450+',
        'impact_page.stat_monthly_1_desc': 'Sustainable businesses launched and supported through the IkiraroBiz entrepreneurship wing.',
        'impact_page.stat_monthly_2_amount': '312+',
        'impact_page.stat_monthly_2_desc': 'Direct beneficiaries currently enrolled in our intensive 2024 empowerment cycle.',
        'impact_page.stat_monthly_3_amount': '85%',
        'impact_page.stat_monthly_3_desc': 'Success rate in long-term economic independence for our program graduates.',
        'resources.breadcrumb_home': 'Home',
        'resources.breadcrumb_resources': 'Resources',
        'resources.title': 'Reports, Research & Media',
        'resources.subtitle': 'Access our latest impact reports, program briefs, and multimedia content showcasing our work across Rwanda.',
        'resources.accountability_badge': 'Accountability',
        'resources.reports_title': 'Annual Reports',
        'resources.strategy_badge': 'Strategy',
        'resources.briefs_title': 'Program Briefs',
        'resources.knowledge_badge': 'Knowledge',
        'resources.research_title': 'Research & Publications',
        'resources.video_badge': 'Video',
        'resources.multimedia_title': 'Multimedia',
        'resources.gallery_badge': 'Gallery',
        'resources.gallery_title': 'Photo Gallery',
        'resources.action_title': 'Impact In Action',
        'resources.action_desc': 'Visual highlights from our operations across the country.',
        'resources.events_badge': 'Events',
        'resources.events_title': 'Upcoming Events & Activities',
        'resources.events_desc': 'Join us at our upcoming events and see our programs in action',
        'resources.who_we_are': 'Who We Are',
        'resources.what_we_do': 'What We Do',
        'resources.why_we_do_it': 'Why We Do It',
        'resources.register_btn': 'Register Interest',
        'resources.learn_more_btn': 'LEARN MORE',
        'resources.latest_badge': 'LATEST',
        'home.mission_lives_changed_count': '150+',
        'home.mission_lives_changed': 'Lives Changed',
        'home.mission_sustainable_impact': 'Sustainable Impact',
        'home.mission_success_rate': '94% Success Rate',
        'contact.title': 'Contact Us',
        'contact.breadcrumb_home': 'Home',
        'contact.breadcrumb_contact': 'Contact',
        'contact.get_in_touch': 'Get in Touch',
        'contact.get_in_touch_desc': 'Have questions about our programs or want to partner with us? Our team is here to support you.',
        'contact.first_name': 'First Name',
        'contact.last_name': 'Last Name',
        'contact.email': 'Email Address',
        'contact.help_label': 'How can we help?',
        'contact.help_placeholder': 'Tell us more about your inquiry...',
        'contact.send_message': 'Send Message',
        'contact.badge': 'Contact Us',
        'contact.conversation_title': 'Let\'s start a conversation',
        'contact.conversation_desc': 'Our team typically responds within 24 hours. Connect with us via email, phone, or visit our office in Bugesera.',
        'contact.office_location': 'Office Location',
        'contact.office_address': 'Bugesera, Nyamata, Rwanda',
        'contact.email_us': 'Email Us',
        'contact.call_support': 'Call Support',
        'contact.cta_title': 'Ready to empower others?',
        'contact.cta_desc': 'Join our community of supporters and make a lasting difference in Rwanda today.',
        'contact.donate_now': 'Donate Now',
        'strategic.hero_title': 'Empower a Future Today',
        'strategic.hero_desc': 'We support girls, caregivers, and youth by promoting education, health, mentorship, and skills development to strengthen families and build resilient communities.',
        'strategic.learn_more': 'Learn More',
        'strategic.impact_title': 'Our impact in 2024',
        'strategic.stat1_label': 'Women & girls reached \n & empowered',
        'strategic.stat2_label': 'Girls stayed in school \n through our support',
        'strategic.stat3_label': 'Businesses launched \n and thriving',
        'strategic.stat4_label': 'Change Champions \n trained as leaders',
        'strategic.title': 'Strategic Direction',
        'strategic.desc1': 'LCEO’s strategic direction defines how we understand change, how we design our programs, and how we achieve results.',
        'strategic.desc2': 'Our work aligns with national and global priorities to achieve sustainable impact for girls and young women, building resilient communities.',
        'strategic.learn_more_btn': 'LEARN MORE',
        'strategic.philosophy_title': 'Our Philosophy',
        'strategic.philosophy_desc': 'LCEO believes that lasting transformation starts with mindset, identity, and mental resilience. We prioritize human capital development through integrated interventions that strengthen confidence, psychosocial wellbeing, education access, and economic empowerment. This approach enables girls and young women to pursue education, achieve economic independence, and emerge as leaders in their communities.',
        'strategic.change_model_badge': 'Change Model',
        'strategic.change_model_title': 'Gender-Transformative Community Change',
        'strategic.change_model_desc': 'LCEO implements its work through the Rugero Rwiza Community Change Model (RR-CCM), a gender-transformative framework that addresses the root causes of inequality at every level of society.',
        'strategic.level1_title': '1. Individual Level',
        'strategic.level1_desc': 'Building agency, confidence, and skills through mindset transformation and education access.',
        'strategic.level2_title': '2. Relational Level',
        'strategic.level2_desc': 'Transforming relationships by engaging male champions and peer mentorship circles.',
        'strategic.level3_title': '3. Structural Level',
        'strategic.level3_desc': 'Addressing systemic barriers through partnerships with local leaders and policy advocacy.',
        'strategic.alignment_title': 'National and Global Alignment',
        'strategic.vision2050_title': 'Rwanda Vision 2050',
        'strategic.vision2050_desc': 'Contributing to human capital development, gender equality, and inclusive economic growth.',
        'strategic.nst2_title': 'NST2 Priorities',
        'strategic.nst2_desc': 'Aligned with Quality education, skills development, and social protection for inclusive growth.',
        'strategic.econ_title': 'Economic Inclusion',
        'strategic.econ_desc': 'Directly contributing to SDG 1 (No Poverty) and SDG 8 (Decent Work) through empowerment.',
        'strategic.gender_title': 'Gender & Education',
        'strategic.gender_desc': 'Fulfilling SDG 4 (Quality Education) and SDG 5 (Gender Equality) for girls to lead.',
        'footer.address_value': 'Bugesera District, Nyamata Sector Eastern Province, Rwanda',
        'footer.phone_value': '+250 788 123 456',
        'footer.email_value': 'info.lceo@gmail.com',
        'footer.brand_name': 'Life-Changing Endeavor Organization.',
        'getinvolved.hero_title': 'Be Part of the Change',
        'getinvolved.hero_desc': 'There are many ways to support LCEO\'s mission to empower vulnerable young women and girls in Rwanda. Find the perfect way for you to make a difference.',
        'getinvolved.stats_banner': 'Every action counts. Join our community of 5,000+ supporters today.',
        'getinvolved.badge': 'Get Involved',
        'getinvolved.title': 'Ways to Support Our Mission',
        'getinvolved.subtitle': 'Choose the way that resonates with you most',
        'getinvolved.impact_circle_title': 'Join Our Impact Circle',
        'getinvolved.impact_circle_desc': 'Become a monthly donor and provide sustained support that transforms lives.',
        'getinvolved.impact_circle_cta': 'Start Monthly Giving',
        'getinvolved.one_time_title': 'Make a One-Time Donation',
        'getinvolved.one_time_desc': 'Every contribution, big or small, makes a real difference in the lives of vulnerable girls.',
        'getinvolved.one_time_cta': 'Donate Now',
        'getinvolved.corporate_title': 'Corporate Partnership',
        'getinvolved.corporate_desc': 'Partner with LCEO to amplify your CSR impact and empower the next generation.',
        'getinvolved.corporate_cta': 'Explore Partnership',
        'getinvolved.volunteer_title': 'Volunteer Your Time',
        'getinvolved.volunteer_desc': 'Share your skills and expertise to mentor, train, or support our programs.',
        'getinvolved.volunteer_cta': 'Apply to Volunteer',
        'getinvolved.sponsor_title': 'Sponsor a Beneficiary',
        'getinvolved.sponsor_desc': 'Directly support a girl\'s education, business, or personal development journey.',
        'getinvolved.sponsor_cta': 'Sponsor a Girl',
        'getinvolved.advocate_title': 'Spread the Word',
        'getinvolved.advocate_desc': 'Amplify our mission by sharing our story on social media and in your networks.',
        'getinvolved.advocate_cta': 'Become an Advocate',
        'getinvolved.monthly_impact_badge': 'Monthly Giving',
        'getinvolved.monthly_impact_title': 'Your Monthly Impact',
        'getinvolved.monthly_impact_desc': 'See how your recurring support transforms lives',
        'getinvolved.support_now_btn': 'SUPPORT NOW',
        'getinvolved.volunteer_with_us': 'Volunteer With Us',
        'getinvolved.volunteer_mission': 'We\'re looking for passionate individuals to share their expertise and mentor the next generation of leaders.',
        'getinvolved.ready_title': 'Ready to Make a Difference?',
        'getinvolved.ready_desc': 'Join hundreds of supporters transforming lives and building sustainable futures for young women in Rwanda.',
        'getinvolved.donate_now_btn': 'DONATE NOW',
        'getinvolved.contact_us_btn': 'CONTACT US',
        'getinvolved.benefit_impact_updates': 'Regular impact updates',
        'getinvolved.benefit_annual_reports': 'Annual beneficiary progress reports',
        'getinvolved.benefit_exclusive_events': 'Invitation to exclusive events',
        'getinvolved.benefit_tax_receipts': 'Tax-deductible receipts',
        'getinvolved.benefit_choose_programs': 'Choose specific programs to support',
        'getinvolved.benefit_immediate_impact': 'Immediate impact',
        'getinvolved.benefit_transparent_funds': 'Transparent fund allocation',
        'getinvolved.benefit_digital_receipt': 'Digital receipt',
        'getinvolved.benefit_co_branded': 'Co-branded initiatives',
        'getinvolved.benefit_employee_engagement': 'Employee engagement opportunities',
        'getinvolved.benefit_reporting': 'Impact measurement & reporting',
        'getinvolved.benefit_visibility': 'Brand visibility',
        'getinvolved.benefit_mentorship_ops': 'Mentorship opportunities',
        'getinvolved.benefit_skills_volunteering': 'Skills-based volunteering',
        'getinvolved.benefit_facilitation': 'Training facilitation',
        'getinvolved.benefit_community_eng': 'Community engagement',
        'getinvolved.benefit_personal_connection': 'Personal connection with beneficiary',
        'getinvolved.benefit_progress_photos': 'Progress updates & photos',
        'getinvolved.benefit_letter_exchange': 'Letter exchanges',
        'getinvolved.benefit_lasting_impact': 'Lasting impact',
        'getinvolved.benefit_social_toolkit': 'Social media toolkit',
        'getinvolved.benefit_shareable_content': 'Shareable content',
        'getinvolved.benefit_ambassador_prog': 'Ambassador program',
        'getinvolved.benefit_community_build': 'Community building',
        'getinvolved.impact_menstrual_kits': 'Provides menstrual hygiene kits for 5 girls for a month',
        'getinvolved.impact_school_fees': 'Supports one girl\'s school fees and supplies for a term',
        'getinvolved.impact_seed_capital': 'Provides seed capital for one woman entrepreneur',
        'getinvolved.impact_full_sponsor': 'Fully sponsors one beneficiary through our complete program',
        'getinvolved.vol_mentorship': 'Mentorship & Coaching',
        'getinvolved.vol_training': 'Business Training',
        'getinvolved.vol_education': 'Educational Support',
        'getinvolved.vol_outreach': 'Community Outreach',
    },
    rw: {
        'nav.home': 'Ahabanza',
        'nav.about': 'Icyo Dukora',
        'nav.about_page': 'Abo Turibo',
        'nav.how_we_work': 'Uko Dukora',
        'nav.impact': 'Ibikorwa n\'Inkurunziza',
        'nav.resources': 'Resources',
        'nav.contact': 'Twandikire',
        'nav.menu': 'Ibikubiyemo',
        'nav.donate': 'Tanga Inkunga',
        'nav.dashboard': 'Ibuye ry\'izahabu',
        'nav.profile': 'Umwirondoro',
        'nav.logout': 'Sohoka',
        'nav.login': 'Injira',
        'nav.strategic_direction': 'Icyerekezo Ndashyikirwa',
        'navbar.mega.donate_title': 'Tanga inkunga uyu munsi',
        'navbar.mega.donate_desc': 'Tanga inkunga aho ikenewe cyane kugira ngo dushoboze abakobwa n\'abagore.',
        'navbar.mega.donate_btn': 'Tanga ubu',
        'navbar.mega.who_we_are': 'Abo Turibo',
        'navbar.mega.our_strategy': 'Intego Zacu',
        'navbar.mega.strategic_direction': 'Icyerekezo Ndashyikirwa',
        'navbar.mega.knowledge_hub': 'Ihuriro ry\'Ubumenyi',
        'navbar.mega.report_title': 'Soma raporo yacu y\'umwaka wa 2024',
        'navbar.mega.report_desc': 'Intego za LCEO, ibikorwa n\'ibyo twagezeho mu 2024 wabisanga muri raporo yacu.',
        'navbar.mega.report_btn': 'Soma raporo',
        'navbar.mega.real_impact': 'Impinduka Nyayo',
        'navbar.mega.help_support': 'Ubufasha n\'Inkunga',
        'navbar.mega.help_faq': 'Ibibazo n\'Ibisubizo',
        'navbar.mega.join_mission_title': 'Fatanya natwe mu rugendo',
        'navbar.mega.join_mission_desc': 'Ba umusemburo w\'impinduka udufashe guhindura ubuzima bwa benshi.',
        'navbar.mega.get_involved_btn': 'Gira uruhare',
        'navbar.mega.get_in_touch': 'Twandikire',
        'navbar.mega.support_lceo': 'Shyigikira LCEO',
        'navbar.user.role': 'Inshingano',
        'donation.trusted_platform': 'Ihuriro ryizerwa rya mbere',
        'donation.starts_here_title': 'Impinduka nziza itangirira hano',
        'donation.btn_start': 'Tangira utange inkunga',
        'donation.stats_title': 'Miliyoni 5 z\'amadolari zirenga zikunze kuboneka buri mwaka muri LCEO.*',
        'donation.stats_desc': 'Tangira mu minota mike — dufite uburyo bwinshi bugufasha guhitamo igikorwa ukunda hanyuma ukagisangiza isi.',
        'donation.make_donation': 'Tanga Inkunga',
        'donation.secure_msg': 'Inkunga yawe irinzwe kandi ihabwa igisoni cy\'imisoro.',
        'donation.select_amount': 'Hitamo Umubare (USD)',
        'donation.custom_amount': 'Andika umubare wihitiyeho',
        'donation.name_placeholder': 'Izina ryawe',
        'donation.email_placeholder': 'Andika Imeri',
        'donation.message_placeholder': 'Ubutumwa bugarura icyizere (Bidahabwa)',
        'donation.btn_donate_now': 'Tanga ${{amount}} Ubu',
        'donation.securing_payment': 'Turimo kurinda ubwishyu...',
        'donation.advanced_options': 'Uburyo bukubiyemo byinshi: Hitamo Gahunda n\'Inkunga ihoraho',
        'donation.impact_circle_title': 'Injira mu itsinda ry\'abatanga impinduka',
        'donation.impact_circle_desc': 'Buri dore imwe ihindura ubuzima mu Karere ka Bugesera mu Rwanda.',
        'donation.step_n_of_m': 'Intambwe ya {{step}} kuri {{total}}',
        'donation.complete_percent': '{{percent}}% Byarangiye',
        'donation.direct_impact_title': 'Hitamo aho ubufasha bwawe bujya',
        'donation.direct_impact_desc': 'Hitamo agace k\'ingenzi ushaka gushyigikira cyangwa utange inkunga aho ikenewe cyane.',
        'donation.where_needed_most': 'Aho ikenewe cyane',
        'donation.where_needed_most_desc': 'Emerera LCEO guhitamo aho inkunga yawe yajya mu bice byihutirwa.',
        'donation.switch_quick': 'Subira ku buryo bwihuse bwo gutanga inkunga',
        'donation.continue': 'Komeza',
        'donation.gift_choice_title': 'Ihitamo ry\'inkunga',
        'donation.gift_choice_desc': 'Shyigikira inshingano zacu binyuze mu nkunga ya buri kwezi cyangwa utange inkunga y\'inshuro imwe.',
        'donation.monthly_giving': 'Inkunga ya buri kwezi',
        'donation.one_time_gift': 'Inkunga y\'inshuro imwe',
        'donation.other_amount': 'Andika undi mubare',
        'donation.back': 'Subira inyuma',
        'donation.about_you_title': 'Icyo twebwe turi cyo',
        'donation.about_you_desc': 'Dufashe kujya tuguha amakuru y\'uko ubufasha bwawe bwatanze impinduka.',
        'donation.full_name': 'Izina ryose',
        'donation.email_address': 'Andika Imeri',
        'donation.message_support': 'Ubutumwa bw\'inkunga (Bidahabwa)',
        'donation.message_community_placeholder': 'Ubutumwa bwawe ku bakobwa no mu baturage...',
        'donation.show_anonymous': 'Inkunga yanjye igaragare nka "Anonymous" ku mbuga rusange',
        'donation.payment_method_title': 'Uburyo bwo kwishyura',
        'donation.payment_method_desc': 'Hitamo uburyo ushaka gukoresha ushyigikira inshingano zacu.',
        'donation.review_donation': 'Subira mu nkunga yawe',
        'donation.review_summary_title': 'Incamake',
        'donation.review_summary_desc': 'Sura neza amakuru y\'inkunga yawe hano munsi.',
        'donation.program_label': 'Gahunda',
        'donation.frequency_label': 'Inshuro',
        'donation.donor_label': 'Umutunzi',
        'donation.payment_label': 'Ubwishyu',
        'donation.total_amount_label': 'Amadolari yose hamwe',
        'donation.terms_privacy': 'Ukanze kuri "Tanga Inkunga Byuzuye", uba wemeye Amategeko n\'Amabwiriza yacu. Amakuru y\'ubwishyu yawe arinzwe neza.',
        'donation.btn_complete': 'Tanga Inkunga Byuzuye',
        'donation.processing': 'Biracyatunganywa...',
        'donation.anonymous': 'Bitazwi',
        'donation.public': 'Kumugaragaro',
        'donation.payment_method': 'Uburyo bwo kwishyura',
        'donation.payment_method_card': 'Ikarita ya Banki',
        'donation.payment_method_card_subtitle': 'Visa, Mastercard, Amex',
        'donation.payment_method_mobile': 'Mobile Money',
        'donation.payment_method_mobile_subtitle': 'MTN, Airtel/Tigo Money',
        'donation.payment_method_bank': 'Kohereza kuri Banki',
        'donation.payment_method_bank_subtitle': 'Kuvana kuri konti ujyana ku yindi',
        'donation.payment_method_paypal': 'PayPal',
        'donation.payment_method_paypal_subtitle': 'Ibwihuse kandi irinzwe',
        'donation.program.education_name': 'Ubufasha mu Burezi',
        'donation.program.education_desc': 'Fasha abakobwa kuguma mu ishuri binyuze mu burere n\'ibikoresho.',
        'donation.program.medical_name': 'Ubuvuzi',
        'donation.program.medical_desc': 'Tanga inyigisho z\'ubuzima n\'ibikoresho by\'isuku mu baturage.',
        'donation.program.business_name': 'Guteza imbere ubucuruzi',
        'donation.program.business_desc': 'Shyigikira abagore b\'abanyamushandiko binyuze mu gishoro n\'amahugurwa.',
        'donation.program.emergency_name': 'Ubutabazi bwihuse',
        'donation.program.emergency_desc': 'Tanga ubufasha bwihuse ku miryango iri mu bihe bigoye.',
        'donation.program.shelter_name': 'Icumbi n\'Umutekano',
        'donation.program.shelter_desc': 'Menya neza ko abagore bafite intege nke bafite aho kuba hizewe.',
        'donation.success_title': 'Murakoze cyane ku buntu bwanyu!',
        'donation.success_subtitle': 'Inkunga yanyu ni intambwe ikomeye mu kurinda agaciro n\'uburenganzira bw\'abagore n\'abakobwa mu Rwanda.',
        'donation.donor_name': 'Izina ry\'umuterankunga',
        'donation.donation_amount': 'Umubare w\'inkunga',
        'donation.transaction_id': 'Transaction ID',
        'donation.date': 'Itariki',
        'donation.next_steps_title': 'Niki gikurikiraho?',
        'donation.next_steps_1': 'Mu kanya barakoherereza imeri yo kwemeza inkunga yawe n\'inyemezabwishyu.',
        'donation.next_steps_2': 'Itsinda ryacu rigiye guhita ryaboherereza iyo nkunga muri gahunda wahisemo.',
        'donation.next_steps_3': 'Guma ku murongo ujye ubona amakuru n\'inkuru z\'impinduka mu baturage uri gufasha.',
        'donation.back_home': 'SUBIRA KURI HOMEPAGE',
        'impact.education_support_short': 'Ibikoresho by\'ishuri ku bakobwa 3',
        'impact.skills_training_short': 'IkiraroBiz Amahugurwa y\'imyuga',
        'impact.starter_kit_short': 'Igishoro cy\'ubucuruzi buciriritse',
        'impact.shelter_safety_short': 'Umwaka umwe w\'icumbi n\'umutekano',
        'hero.title': 'Kurinda Agaciro n\'Uburenganzira bw\'Abagore n\'Abakobwa',
        'hero.subtitle': 'Tushyigikira abakobwa, ababyeyi, n\'urubyiruko binyuze mu burezi, ubuzima, no guhugura imyuga.',
        'mission.badge': 'Inshingano Zacu',
        'mission.title': 'Kurinda Agaciro n\'Uburenganzira bw\'Abagore n\'Abakobwa.',
        'mission.desc': 'Binyuze mu burere, inkunga y\'ubushabitsi, cyangwa ubufasha mu buzima bwo mu mutwe, dutanga ubufasha bwuzuye bukenewe kugira ngo duhindure ubuzima. Kuva mu bikorwa byo mu baturage kugeza ku buvugizi bukomeye, dufasha abagore n\'abakobwa batishoboye guhindura imbogamizi zabo mu bikorwa bifatika, kubaka icyizere, no kwihutisha urugendo rwabo rwo kwigira mu Bugesera no hirya no hino.',
        'mission.empowerment': 'Iterambere ry\'Ubukungu',
        'mission.education': 'Uburyo bwo Kwiga',
        'mission.health': 'Ubufasha mu Buzima bwo mu Mutwe',
        'mission.advocacy': 'Ubuvugizi mu Baturage',
        'mission.learn_more': 'Menya Byinshi kuri Twe',
        'impact.heading': 'Ibikorwa mu Mibare',
        'impact.women': 'Abagore n\'abakobwa bafashijwe',
        'impact.education': 'Abakobwa bagumye mu ishuri ku bw\'inkunga yacu',
        'impact.livelihoods': 'Imishinga yatangijwe kandi itera imbere',
        'impact.leadership': 'Abayobozi batowe mu baturage',
        'programs.subheading': 'Gahunda Zacu',
        'programs.heading': 'Ibikorwa Bifashije',
        'programs.desc': 'Twibanda ku bice by\'ingenzi bidufasha guhindura ubuzima bw\'abagore n\'imiryango yabo mu buryo burambye.',
        'programs.view_all': 'REBA GAHUNDA ZACU ZOSE',
        'stories.subheading': 'Inkurunziza',
        'stories.heading': 'Inkuru z\'Impinduka',
        'stories.desc': 'Ibuka impinduka zikomeye mu buzima bw\'abo dufasha.',
        'gallery.heading': 'Igalari ry\'Amafoto',
        'footer.stay_connected': 'Guma hafi yacu',
        'footer.newsletter_desc': 'Andikisha imeri yawe kugira ngo ujye ubona amakuru mashya n\'inkuru nshya',
        'footer.email_placeholder': 'Andika imeri yawe',
        'footer.subscribe': 'Andikisha',
        'footer.brand_desc': 'Gushoboza abakobwa n\'abagore batishoboye mu Rwanda binyuze mu burezi, ubushabitsi, n\'ubuzima.',
        'footer.quick_links': 'Inzira zihuse',
        'footer.get_involved': 'Gira uruhare',
        'footer.contact_us': 'Twandikire',
        'footer.address_label': 'Icyerekezo',
        'footer.phone_label': 'Telefoni',
        'footer.email_label': 'Imeri',
        'footer.copyright': 'Uburenganzira bwose burasigasiriwe.',
        'footer.monthly_giving': 'Inkunga ya buri kwezi',
        'footer.volunteer': 'Iba Umukorerabushake',
        'footer.partner_with_us': 'Fatanya Natwe',
        'btn.learn_more': 'Menya Byinshi',
        'btn.donate': 'Tanga Inkunga',
        'home.impact_heading': 'Incamake y\'ibyo twagezeho mu Karere ka Bugesera',
        'home.impact_women': 'Abagore n\'abakobwa bafashijwe',
        'home.impact_education': 'Abakobwa bagumye mu ishuri ku bw\'inkunga yacu',
        'home.impact_livelihoods': 'Imishinga yatangijwe kandi itera imbere',
        'home.impact_leadership': 'Abayobozi batowe mu baturage',
        'home.mission_badge': 'Inshingano Zacu',
        'home.mission_title': 'Kurinda Agaciro n\'Uburenganzira bw\'Abagore n\'Abakobwa.',
        'home.mission_desc': 'Binyuze mu burere, inkunga y\'ubushabitsi, cyangwa ubufasha mu buzima bwo mu mutwe, dutanga ubufasha bwuzuye bukenewe kugira ngo duhindure ubuzima.',
        'home.mission_empowerment': 'Iterambere ry\'Ubukungu',
        'home.mission_education': 'Uburyo bwo Kwiga',
        'home.mission_health': 'Ubufasha mu Buzima bwo mu Mutwe',
        'home.mission_advocacy': 'Ubuvugizi mu Baturage',
        'home.mission_learn_more': 'Menya Byinshi kuri Twe',
        'home.impact_areas_badge': 'IBICE BY\'INGENZI TWIBANDAHO',
        'home.programs_view_all': 'REBA GAHUNDA ZACU ZOSE',
        'home.impact_areas_title': 'Ingamba zo Guteza Imbere Imibereho Ishyize Hamwe',
        'home.impact_areas_emergency_title': 'Ubutabazi bwihuse',
        'home.impact_areas_emergency_desc': 'Gutanga ubufasha bwihuse bw\'ubutabazi n\'ubwirinzi ku miryango iri mu kaga.',
        'home.impact_areas_economic_title': 'Iterambere ry\'Ubukungu',
        'home.impact_areas_economic_desc': 'Kubaka ejo hazaza heza binyuze mu nyigisho z\'imicungire y\'imari, ubushabitsi, no guhanga amasoko.',
        'home.impact_areas_srhr_title': 'Ubuzima bw\'Imyororokere n\'Isuku',
        'home.impact_areas_srhr_desc': 'Gusigasira agaciro k\'umukobwa binyuze mu bikorwa by\'isuku n\'inyigisho ku buzima bw\'imyororokere.',
        'home.impact_areas_education_title': 'Uburere n\'Ibuguma mu Ishuri',
        'home.impact_areas_education_desc': 'Kumenya neza ko buri mukobwa uguma mu ishuri binyuze mu nkunga n\'ukurikirana imitsindire ye.',
        'home.impact_areas_gender_title': 'Uburinganire n\'Ubwirinzi',
        'home.impact_areas_gender_desc': 'Kurwanya ihohoterwa rishingiye ku gitsina no guteza imbere uburenganzira bw\'abagore mu muryango.',
        'home.impact_areas_human_title': 'Imbaraga z\'Abaturage n\'Icyizere',
        'home.impact_areas_human_desc': 'Gufasha abagore n\'abakobwa mu Rwanda kugira ubumenyi mu buyobozi n\'icyizere kihamye.',
        'home.stories_journey_suffix': " ashora ejo hazaza n'iterambere rya bagenzi be",
        'home.stories_read_more': 'SOMA IZINDI NKURU ZOSE',
        'home.partners_heading': 'Abafatanyabikorwa mpuzamahanga bakorana na LCEO buri munsi.',
        'home.partner_fawe_subtitle': 'Ihuriro ry\'abagore baharanira uburezi muri Afurika',
        'home.partner_ecorys_subtitle': 'Umujyanama mu iterambere mpuzamahanga',
        'home.partner_mor_subtitle': 'Ubufatanyabikorwa bw\'ingamba n\'iterambere',
        'home.impact_circle_badge': 'Shyigikira Impinduka Ramba',
        'home.impact_circle_title': 'Injira mu Itsinda ry\'Imbaraga',
        'home.impact_circle_desc': 'Inkunga yawe ya buri kwezi ifasha mu guhindura ubuzima bw\'abakobwa n\'abagore batishoboye mu Rwanda.',
        'home.impact_circle_tier1_price': '$25/kukwesi',
        'home.impact_circle_tier1_desc': 'Fasha abakobwa 5 mu kigo cy\'isuku buri kwezi, kugira ngo batigera basiba ishuri.',
        'home.impact_circle_btn': 'INJIRA MU ITSINDA',
        'home.impact_circle_tier2_price': '$50/kukwesi',
        'home.impact_circle_tier2_desc': 'Rihira umukobwa umwe ishuri kandi umuhe ibikoresho byose akeneye.',
        'home.impact_circle_btn_alt': 'INJIRA UBU',
        'home.impact_circle_tier3_price': '$100/kukwesi',
        'home.impact_circle_tier3_desc': 'Tanga igishoro n\'amahugurwa ku mugore w\'umunyamushandiko kugira ngo atangire ubucuruzi bwe.',
        'home.sdg_title': 'Gushoboza Ubuzima + Gukomeza Imiryango Binyuze mu Ntego Rusange',
        'home.sdg_desc1': 'Muri LCEO, twemera ko iterambere rirambye rishoboka gusa iyo duhuje imbaraga zacu n\'iz\'isi yose. Twibanda kuri izi ntego z\'iterambere rirambye kugira ngo buri nkunga y\'ishuri, buri gishoro cy\'ubucuruzi, n\'ubufasha mu buzima bwo mu mutwe bigire uruhare mu cyerekezo cy\'icyubahiro n\'uburinganire kuri bose.',
        'home.sdg_desc2': 'Uburyo bwacu mu Karere ka Bugesera bugira uruhare mu guhindura ubuzima bw\'ibihumbi, buhuza imbogamizi zo mu baturage n\'ibyerekezo mpuzamahanga by\'ubutabera n\'iterambere.',
        'home.sdg_report_btn': 'Reba Raporo y\'Ibikorwa →',
        'home.sdg_goal_label': 'Intego',
        'home.movement_badge': 'Twisunge mu RUGENDO',
        'home.movement_title': 'Ba Umusemburo w\'Impinduka',
        'home.movement_desc': 'Waba utanga umwanya wawe cyangwa ubufasha, uba ushora mu bihe hazaza aho buri mwana w\'umukobwa ashobora gutera imbere.',
        'home.movement_donor_title': 'Umuterankunga mu by\'Imari',
        'home.movement_donor_desc': 'Shyigikira inshingano zacu binyuze mu nkunga y\'inshuro imwe cyangwa ihoraho ifasha mu burere n\'ibishoro.',
        'home.movement_volunteer_title': 'Umukorerabushake ufite ubumenyi',
        'home.movement_volunteer_desc': 'Sangiza ubumenyi bwawe mu buvuzi, uburezi, cyangwa ubucuruzi utanga amahugurwa n\'inama.',
        'home.movement_partner_title': 'Umufatanyabikorwa',
        'home.movement_partner_desc': 'Fatanya na LCEO kwagura uburyo bwacu bwo gushoboza abaturage mu bice bishya n\'imiryango mishya.',
        'home.movement_advocacy_title': 'Umuvugizi mu Baturage',
        'home.movement_advocacy_desc': 'Kwamamaza no guharanira uburenganzira bw\'abakobwa n\'abagore mu Karere ka Bugesera.',
        'home.movement_form_badge': 'Injira Natwe Ubu',
        'home.movement_form_title': 'Ba Umukorerabushake',
        'home.movement_name_placeholder': 'Izina ryawe',
        'home.movement_email_placeholder': 'Imeri yawe',
        'home.movement_phone_placeholder': 'Telefoni',
        'home.movement_location_placeholder': 'Aho uherereye',
        'home.movement_message_placeholder': 'Ubutumwa bwawe',
        'home.movement_btn': 'Ba Umukorerabushake',
        'home.sdg_goal1:': 'Kurandura Ubukene',
        'home.sdg_goal3': 'Ubuzima bwiza',
        'home.sdg_goal4': 'Uburezi bufite ireme',
        'home.sdg_goal5': 'Uburinganire',
        'home.sdg_goal8': 'Umurimo unoze',
        'home.sdg_goal10': 'Kugabanya ubusumbane',
        'programs.p1.title': 'Uburere n\'Ibuguma mu Ishuri',
        'programs.p1.description': 'Gukuraho imbogamizi zibuza abakobwa kwiga binyuze mu buryo bwuzuye bwo kubashyigikira.',
        'programs.p1.subtitle': 'Uburezi Bufite Intego',
        'programs.p1.features_title': 'Iby\'ingenzi biherereyeho:',
        'programs.p1.feature1': 'Inkunga y\'ishuri yose',
        'programs.p1.feature2': 'Ibikoresho n\'imyambaro y\'ishuri',
        'programs.p1.feature3': 'Amahugurwa n\'ubujyanama',
        'programs.p1.feature4': 'Guhuza ababyeyi n\'ishuri',
        'programs.p1.status': 'Bikorwa mu Bugesera',
        'programs.p2.title': 'Iterambere ry\'Ubukungu',
        'programs.p2.description': 'Gushoboza abagore b\'abanyamushandiko bafite ibikoresho n\'igishoro cyo kubaka ubucuruzi burambye.',
        'programs.p2.subtitle': 'Gushyigikira Imibereho',
        'programs.p2.features_title': 'Inkingi za Gahunda:',
        'programs.p2.feature1': 'Inkunga y\'igishoro',
        'programs.p2.feature2': 'Inyigisho z\'ubucuruzi',
        'programs.p2.feature3': 'Guhuza n\'amasoko',
        'programs.p2.feature4': 'Gushinga amatsinda yo kuzigama',
        'programs.p2.status': 'Imishinga 150+ yatewe inkunga',
        'programs.p3.title': 'Ubufasha mu Buzima bw\'Umubiri n\'umutwe',
        'programs.p3.description': 'Guhuza ubuzima bwo mu mutwe n\'ubw\'imyororokere mu iterambere ry\'abaturage.',
        'programs.p3.subtitle': 'Ubuzima n\'Agaciro',
        'programs.p3.features_title': 'Serivisi Zitangwa:',
        'programs.p3.feature1': 'Ibikoresho by\'isuku y\'abakobwa',
        'programs.p3.feature2': 'Ubujyanama mu by\'idini',
        'programs.p3.feature3': 'Amahugurwa ku buzima',
        'programs.p3.feature4': 'Kumenya uburenganzira bw\'imyororokere',
        'programs.p3.status': 'Kwagura Ibikorwa',
        'about.title': 'Abo Turibo LCEO',
        'about.breadcrumb_home': 'Ahabanza',
        'about.breadcrumb_about': 'Abo Turibo',
        'about.team_caption_title': 'Uburezi, Ubushabitsi, n\'Inama',
        'about.team_caption_subtitle': 'Bitangwa n\'Ikipe Yitaye ku Bakiriya',
        'about.badge': 'Abo Turibo',
        'about.title_impact_prefix': 'Kubaka Impinduka Ramba ku ',
        'about.title_impact_highlight': 'Nshingano Zidufitiye Akamaro',
        'about.description': 'Life-Changing Endeavor Organization (LCEO) ni umuryango utegamiye kuri leta ufite icyicaro i Kigali, utanga serivisi z\'uburezi, ubuzima, n\'iterambere ry\'ubukungu binyuze mu ikipe imwe ishyize hamwe. Twizerwa n\'abaturage bo mu Rwanda hose, twubaka uburyo burambye n\'imishinga igamije iterambere itanga umusaruro ugaragara ku muntu.',
        'about.vision_tab': 'Icyerekezo Cyacu',
        'about.mission_tab': 'Inshingano Zacu',
        'about.vision_desc': 'Umuryango aho abagore n\'abakobwa bafite imbaraga mu mutwe, bari bize, kandi bafite ubushobozi mu bukungu — bafite umudendezo wo kuyobora no gutera imbere mu muryango wabo.',
        'about.mission_desc': 'Guherekeza abakobwa n\'abagore mu gihe bakira, bakura, kandi batera imbere — binyuze mu guhindura imitekerereze, gukomera mu mutwe, uburezi bufite ireme, n\'iterambere ry\'ubukungu rirambye.',
        'about.foundation_badge': 'Umusingi Wacu',
        'about.values_title': 'Indangagaciro Zacu',
        'about.values_heading_prefix': 'Tuyobowe n\'Intego, Dusunikwa n\'',
        'about.values_heading_highlight': 'Impinduka',
        'about.values_desc': 'Amahame agenga akazi kacu n\'uburyo twiyemeje gufasha abagore n\'abakobwa bafite intege nke mu Rwanda.',
        'about.value_empowerment_title': 'Guha Ubushobozi',
        'about.value_empowerment_desc': 'Gufungura ubushobozi buri muri buri mukobwa kugira ngo ayobore.',
        'about.value_protection_title': 'Uburinzi',
        'about.value_protection_desc': 'Gushyiraho ahantu hizewe, boroshye hagamije gukira no gukura.',
        'about.value_innovation_title': 'Ihanga',
        'about.value_innovation_desc': 'Gukoresha uburyo bushingiye ku bimenyetso n\'udushya mu guhindura ubuzima.',
        'about.value_compassion_title': 'Ibwirizwa',
        'about.value_compassion_desc': 'Guherekeza abagenerwabikorwa bacu twumva amarangamutima yabo kandi tububaha.',
        'about.value_community_title': 'Umuryango',
        'about.value_community_desc': 'Kubaka ihuriro rirambye ry\'ubufasha mu gace n\'imahanga.',
        'about.value_excellence_title': 'Indashyikirwa',
        'about.value_excellence_desc': 'Wiyemeje gutanga umusaruro ugaragara kandi urambye ku bantu.',
        'about.value_card_badge': 'Ihame ry\'Ingenzi',
        'about.value_card_footer': 'Ubufasha bwa LCEO',
        'about.read_more_btn': 'SOMA BYINSHI',
        'about.journey_btn': 'Ba mu Rugendo Rwacu',
        'about.team_badge': 'Hura n\'Ikipe Yacu',
        'about.team_title': 'Abantu Bari Inyuma ya LCEO',
        'about.team_role_sarah': 'Umuyobozi Mukuru',
        'about.team_bio_sarah': 'Afite uburambe bw\'imyaka barenga 15 mu iterambere no guha ubushobozi abantu mu Rwanda.',
        'about.team_role_jean': 'Umuyobozi wa Gahunda',
        'about.team_bio_jean': 'Inzobere mu burezi n\'iterambere ry\'urubyiruko mu baturage.',
        'about.team_role_grace': 'Umuyobozi w\'Imari',
        'about.team_bio_grace': 'Kureba ko imari ikoreshwa mu mucyo, mu buryo bubajijwe, kandi burambye.',
        'about.team_role_emmanuel': 'Inzobere mu Gukurikirana n\'Isuzuma',
        'about.team_bio_emmanuel': 'Uburyo bushingiye ku makuru mu gupima no kunoza imikorere ya gahunda.',
        'about.progress_badge': 'Iterambere',
        'about.progress_title': 'Ibyo Twagezeho n\'Ibikorwa By\'Indashyikirwa',
        'about.milestone_2020_title': 'Fondasiyo ya LCEO',
        'about.milestone_2020_desc': 'Iyandikishwa mu Karere ka Bugesera n\'icyerekezo cyo guhindura ubuzima binyuze mu mitekerereze.',
        'about.milestone_2021_title': 'Itangira rya Gahunda ya mbere',
        'about.milestone_2021_desc': 'Gahunda yo gutuma abakobwa baguma mu ishuri yageze ku banyeshuri 50 ba mbere.',
        'about.milestone_2022_title': 'Mushinga wa IkiraroBiz',
        'about.milestone_2022_desc': 'Impinduka ikomeye mu bushabitsi, ifasha abagore 30 gutangiza imishinga irambye.',
        'about.milestone_2023_title': 'Kwagura Ibikorwa',
        'about.milestone_2023_desc': 'Kwagurira ibikorwa mu uturere twinshi, tugera ku bagenerwabikorwa barenga 200.',
        'about.milestone_2024_title': 'Kumenyekana n\'Iterambere',
        'about.milestone_2024_desc': 'Gusinya amasezerano y\'ubufatanye na FAWE Rwanda, ubu turafasha abagenerwabikorwa 312.',
        'about.image_impact_label': 'Impinduka 2023',
        'about.image_journey_label': 'Urugendo Rwacu',
        'about.legacy_label': 'Umurage',
        'work.breadcrumb_home': 'Ahabanza',
        'work.breadcrumb_work': 'Uko Dukora',
        'work.title': 'Uko Dukora',
        'work.more_ways_title': 'Uburyo bwinshi bwo gushyigikira LCEO',
        'work.support_will': 'Siga umunani mu irage ryawe',
        'work.support_regular': 'Tanga inkunga ihoraho',
        'work.support_fundraise': 'Kusanya inkunga ya LCEO',
        'work.support_corporate': 'Ba umufatanyabikorwa mu bucuruzi',
        'work.story_badge': 'Inkuru',
        'work.featured_story_title': 'Inshingano zacu zo kurinda no gushoboza, bisobanuye',
        'work.featured_story_desc': 'Byavuguruwe mu 2026: Vumbura inkingi eshanu z\'ingenzi ziyoboye impinduka ziyobowe n\'abaturage n\'uburyo twagura ibyo dukora.',
        'work.secondary_story_title': 'Ingaruka z\'ubujyanama bwuzuye',
        'work.secondary_story_desc': 'Abayobozi b\'abaturage basobanura uko uburyo bwacu bwuzuye buri guhanga impinduka ramba mu midugudu.',
        'work.impact_badge': 'Ibice Twibandaho',
        'work.impact_title': 'Ibice by\'Ubutabazi',
        'work.impact_desc': 'LCEO ikorera mu bice byinshi by\'ingamba kugira ngo ihange ibidukikije birinda kandi bishoboza.',
        'work.area_edu_title': 'Uburere n\'Ibuguma mu Ishuri',
        'work.area_edu_desc': 'Kumenya neza ko buri mukobwa afite ibikoresho n\'ubufasha bwo kuguma mu ishuri binyuze mu bikorwa by\'abaturage.',
        'work.area_srhr_title': 'SRHR n\'Agaciro',
        'work.area_srhr_desc': 'Gutanga ubumenyi bwuzuye n\'ibikoresho by\'ubuzima bw\'imyororokere n\'agaciro mu gihe cy\'imihango.',
        'work.area_gender_title': 'Uburinganire n\'Ubwirinzi',
        'work.area_gender_desc': 'Guharanira uburenganzira no kurinda abakobwa ihohoterwa n\'inda zitateganyijwe binyuze mu butabera.',
        'work.area_econ_title': 'Iterambere ry\'Ubukungu',
        'work.area_econ_desc': 'Kubaka imibereho y\'abagore banyamushandiko binyuze mu mahugurwa y\'imyuga n\'uburyo bwo kugera ku masoko.',
        'work.area_resilience_title': 'Icyizere Cyitekererezwa',
        'work.area_resilience_desc': 'Kwibanda ku buzima bwo mu mutwe n\'ubuyobozi binyuze mu bujyanama n\'amahugurwa y\'imitekerereze.',
        'work.area_emergency_title': 'Ubutabazi bwihuse',
        'work.area_emergency_desc': 'Gutanga ubufasha bwihuse ku bakobwa n\'abagore bari mu kaga binyuze muryo bwihuse.',
        'work.methodology_badge': 'Uburyo Dukoresha',
        'work.methodology_title': 'Urugendo rwa LCEO',
        'work.methodology_desc': 'Uburyo bwa Rugero Rwiza (RR-CCM) ni uburyo bwacu bwite, bwubatswe kugira ngo buvane abaturage mu kaga bagezwe ku kwigira kuzuye binyuze mu ntambwe zubahirijwe.',
        'work.engine_title': 'Moteri y\'Impinduka mu Muryango.',
        'work.engine_desc': 'Uburyo bwacu si ibikorwa gusa; ni moteri y\'ingamba yubatswe kugira ngo mace iminyururu y\'ubukene n\'ubusumbane dushingiye ku gitsina.',
        'work.engine_quote': 'Impinduka ramba ibaho gusa iyo abaturage bigize igisubizo cyabo.',
        'work.certified_badge': 'Uburyo bwemejwe',
        'work.process_step1_title': 'Icyiciro cyo Kuvumbura',
        'work.process_step1_desc': 'Kutarama mu baturage kugira ngo dusobanukirwe imico n\'ubushobozi bw\'ubuyobozi bw\'ibanze.',
        'work.process_step2_title': 'Ubumenyi bwuzuye',
        'work.process_step2_desc': 'Gukoresha amakuru menshi kugira ngo tumenye ibikenewe mu burezi, ubuzima, n\'ubukungu.',
        'work.process_step3_title': 'Gukoranira hamwe Umushinga',
        'work.process_step3_desc': 'Guhanga ibisubizo dufatanije n\'abaturage kugira ngo byakirwe neza kandi bijyanye n\'umuco.',
        'work.process_step4_title': 'Gushira mu bikorwa by\'Imyaka Myinshi',
        'work.process_step4_desc': 'Gukoresha ubutabazi bukomeye mu nzego nyinshi icyarimwe kugira ngo tugere ku ntego.',
        'work.process_step5_title': 'Gukurikirana ku buryo buhoraho',
        'work.process_step5_desc': 'Gutanga ibitekerezo no gupima impinduka kugira ngo tunonosore ingamba mu gihe gikwiye.',
        'work.process_step6_title': 'Kuramba ku buryo bwiciye mu byiciro',
        'work.process_step6_desc': 'Guhererekanya ubuyobozi n\'abaturage bahuguwe kugira ngo umushinga ukomeze nubwo LCEO yaba itagihari.',
        'work.framework_title': 'Ingamba Zerekanwe',
        'work.framework_desc': 'Urugendo rwacu rugaragarira mu byiciro by\'ibikorwa.',
        'work.download_btn': 'Manura PDF',
        'work.phase1_title': 'Icyiciro I: Fondasiyo',
        'work.phase1_desc': 'Kwibanda ku kubaka icyizere, amategeko, n\'uburyo bwo kwinjira mu baturage. Twubaka Rugero Rwiza Hubs nka santire z\'impinduka.',
        'work.phase2_title': 'Icyiciro II: Impinduka',
        'work.phase2_desc': 'Igihe cyo gushyira mu bikorwa inkunga y\'ishuri, ubuzima bwo mu mutwe, n\'ubujyanama buri munsi.',
        'work.phase3_title': 'Icyiciro III: Kuramba',
        'work.phase3_desc': 'Icyiciro cya nyuma cyibanda ku buyobozi bw\'ibanze, koperative, n\'isoko ryigenga ry\'abagenerwabikorwa.',
        'work.principles_title': 'Inkingi z\'Ubutabazi',
        'work.principles_desc': 'Agaciro kayobora buri ntambwe y\'urugendo rwacu rw\'ibikorwa.',
        'work.principle1_title': 'Kwigira kw\'Abaturage',
        'work.principle1_desc': 'Ntitwemera "gukiza" abaturage. Twemera kubashoboza biyoborera impinduka zabo.',
        'work.principle2_title': 'Kwibanda ku bintu byose',
        'work.principle2_desc': 'Tureba imbogamizi zifatanije z\'igitsina, ubukene, n\'aho umuntu aherereye kugira ngo nta mukobwa usigara inyuma.',
        'work.principle3_title': 'Gushingira ku Makuru',
        'work.principle3_desc': 'Buri gahunda ishingiye ku makuru afatika n\'ibisubizo nyabyo, bituma habaho imitangire myiza.',
        'work.principle4_title': 'Gukorera mu Mucyo',
        'work.principle4_desc': 'Tuguma gukorera mu mucyo ku bagenerwabikorwa bacu, abafatanyabikorwa, n\'isi yose.',
        'work.results_title': 'Uburyo mu Bikorwa: Ibyagezweho',
        'work.results_desc': 'Uburyo bwa Rugero Rwiza buri gutanga ibisubizo bishobora gupimwa kandi bihindura ubuzima hano.',
        'work.stat1_label': 'Abakobwa Bashobojwe',
        'work.stat1_desc': 'Abagenerwabikorwa b\'ibyo dukora mu burezi n\'ubuzima bwo mu mutwe.',
        'work.stat2_label': 'Rugero Rwiza Hubs',
        'work.stat2_desc': 'Santire z\'abaturage zikora nk\'ahantu hizewe ho kwigira n\'ubujyanama.',
        'work.stat3_label': 'Ibuguma mu Ishuri',
        'work.stat3_desc': 'Ku bakobwa bahabwa inkunga baguma mu ishuri kugeza barangije.',
        'work.stat4_label': 'Abajyanama b\'Abaturage',
        'work.stat4_desc': 'Abayobozi b\'abaturage bahuguwe bakomeza uyu mushinga.',
        'work.sdg_title': 'Intego za SDG Zihuye',
        'work.sdg_desc': 'LCEO igira uruhare mu ntego z\'iterambere rirambye za Loni.',
        'work.sdg1': 'SDG 1: Kurandura Ubukene',
        'work.sdg3': 'SDG 3: Ubuzima Kuzira Aze',
        'work.sdg4': 'SDG 4: Uburezi Bufite Ireme',
        'work.sdg5': 'SDG 5: Uburinganire',
        'work.sdg8': 'SDG 8: Umurimo Unoze',
        'work.sdg10': 'SDG 10: Kugabanya Ubusumbane',
        'impact_page.breadcrumb_home': 'Ahabanza',
        'impact_page.breadcrumb_impact': 'Impinduka & Inkuru',
        'impact_page.title': 'Guhindura Ubuzima, Kubaka Ejo Hazaza',
        'impact_page.subtitle': 'Buri mibare ihagarariye ubuzima bwahindutse. Buri mubare uvuga inkuru y\'icyizere, gukura, n\'ubushobozi.',
        'impact_page.badge_lceo': 'Ibijyanye na LCEO',
        'impact_page.heading': 'Dufatanije, Tuzana Impinduka!',
        'impact_page.description': 'Buri mibare ihagarariye ubuzima bwahindutse. Reba impinduka nyazo z\'imirimo ya LCEO mu burezi, kwihangira imirimo, n\'ubushobozi. Twemera kubaka ejo hazaza rirambye kuri buri mukobwa mu Rwanda.',
        'impact_page.btn_donate': 'Tanga Inkunga Ifite Akamaro',
        'impact_page.donate_now_heading': 'Tanga nonaha',
        'impact_page.exit_site_btn': 'Sohoka',
        'impact_page.sdg_badge': 'Intego ku Isi',
        'impact_page.sdg_title': 'Bijyanye n\'Intego Mpuzamahanga',
        'impact_page.sdg_desc': 'Gahunda za LCEO zigira uruhare ruziguye mu ntego za 2030 z\'iterambere rirambye mu Rwanda.',
        'impact_page.resilience_title': 'Icyizere Cy\'Abaturage',
        'impact_page.resilience_desc': 'Kubaka ubuzima, uburere, n\'ituze ku miryango itishoboye mu Rwanda.',
        'impact_page.transformation_title': 'Impinduka mu Muryango',
        'impact_page.transformation_desc': 'Guharanira uburinganire n\'igabanuka ry\'ubusumbane binyuze mu buvugizi.',
        'impact_page.report_btn': 'Reba Raporo Irambuye',
        'impact_page.partner_btn': 'Fatanya n\'Inshingano Zacu',
        'impact_page.outcomes_title': 'Ibyagezweho mu Ngamba',
        'impact_page.outcome_item1': 'Kuziba icyuho mu tekinepoloji',
        'impact_page.outcome_item2': 'Inzira z\'ubukungu',
        'impact_page.outcome_item3': 'Ubuvugizi mu baturage',
        'impact_page.outcome_item4': 'Kwishyira hamwe kwa politiki',
        'impact_page.outcome_item5': 'Modeli z\'ibuguma',
        'impact_page.outcome_item6': 'Santire z\'urugero',
        'impact_page.tab_one_off': 'Impinduka y\'Igihe Gito',
        'impact_page.tab_monthly': 'Impinduka ya Buri Kwezi',
        'impact_page.explore_btn': 'Vumbura inkuru z\'impinduka nyinshi uyu munsi',
        'impact_page.stat_one_off_1_amount': '5,000+',
        'impact_page.stat_one_off_1_desc': 'Abakobwa bahuguwe mu burezi no mu muryango.',
        'impact_page.stat_one_off_2_amount': '1,200+',
        'impact_page.stat_one_off_2_desc': 'Abakobwa bafashijwe kuguma mu ishuri neza.',
        'impact_page.stat_one_off_3_amount': '300+',
        'impact_page.stat_one_off_3_desc': 'Abashinzwe guhindura imitekerereze mu baturage.',
        'impact_page.stat_monthly_1_amount': '450+',
        'impact_page.stat_monthly_1_desc': 'Imishinga itanga akazi yashyigikiwe.',
        'impact_page.stat_monthly_2_amount': '312+',
        'impact_page.stat_monthly_2_desc': 'Abagenerwabikorwa bari mu mahugurwa uyu munsi.',
        'impact_page.stat_monthly_3_amount': '85%',
        'impact_page.stat_monthly_3_desc': 'Igipimo cyo kwigira ku barangije amahugurwa.',
        'resources.breadcrumb_home': 'Ahabanza',
        'resources.breadcrumb_resources': 'Resources',
        'resources.title': 'Raporo, Ubushakashatsi & Ifoto/Amashusho',
        'resources.subtitle': 'Gana raporo zacu nshya, incamake za gahunda, n\'amashusho yerekana imirimo yacu mu Rwanda.',
        'resources.accountability_badge': 'Uburyozwacyaha',
        'resources.reports_title': 'Raporo z\'Umwaka',
        'resources.strategy_badge': 'Ingamba',
        'resources.briefs_title': 'Incamake za Gahunda',
        'resources.knowledge_badge': 'Ubumenyi',
        'resources.research_title': 'Ubushakashatsi & Ibitangazwa',
        'resources.video_badge': 'Amashusho',
        'resources.multimedia_title': 'Multimedia',
        'resources.gallery_badge': 'Gallery',
        'resources.gallery_title': 'Photo Gallery',
        'resources.action_title': 'Ibikorwa mu Mashusho',
        'resources.action_desc': 'Ibikorwa by\'indashyikirwa byacu mu gihugu hose.',
        'resources.events_badge': 'Ibirori',
        'resources.events_title': 'Ibirori & Ibikorwa Bitaha',
        'resources.events_desc': 'Fatanya natwe mu birori bitaha urebe gahunda zacu mu bikorwa',
        'resources.who_we_are': 'Abo Turibo',
        'resources.what_we_do': 'Icyo Dukora',
        'resources.why_we_do_it': 'Impamvu Tubikora',
        'resources.register_btn': 'Iyandikishe',
        'resources.learn_more_btn': 'MENYA BYINSHI',
        'resources.latest_badge': 'NSHYA',
        'home.mission_lives_changed_count': '150+',
        'home.mission_lives_changed': 'Ubuzima bwahindutse',
        'home.mission_sustainable_impact': 'Impinduka Ramba',
        'home.mission_success_rate': '94% Itsinda ryagezweho',
        'contact.title': 'Twandikire',
        'contact.breadcrumb_home': 'Ahabanza',
        'contact.breadcrumb_contact': 'Twandikire',
        'contact.get_in_touch': 'Vugana natwe',
        'contact.get_in_touch_desc': 'Ufite ibibazo cyangwa urashaka ko dukorana? Ikipe yacu iri hano kugira ngo igufashe.',
        'contact.first_name': 'Izina rya mbere',
        'contact.last_name': 'Izina rya kabiri',
        'contact.email': 'Imeri',
        'contact.help_label': 'Twagufasha ute?',
        'contact.help_placeholder': 'Tubwire birambuye icyo wifuza...',
        'contact.send_message': 'Yohereza ubutumwa',
        'contact.badge': 'Twandikire',
        'contact.conversation_title': 'Reka dutangire ikiganiro',
        'contact.conversation_desc': 'Ikipe yacu isubiza mu masaha 24. Twandikire kuri imeri, telefone, cyangwa usure ibiro byacu muri Bugesera.',
        'contact.office_location': 'Ibiro Byacu',
        'contact.office_address': 'Bugesera, Nyamata, Rwanda',
        'contact.email_us': 'Twandikire kuri Imeri',
        'contact.call_support': 'Duhamagare',
        'contact.cta_title': 'Witeguye gushoboza abandi?',
        'contact.cta_desc': 'Fatanya n\'abaterankunga bacu uhindure ubuzima mu Rwanda uyu munsi.',
        'contact.donate_now': 'Tanga Inkunga Nonaha',
        'strategic.hero_title': 'Shoboza Ejo Hazaza Uyu Munsi',
        'strategic.hero_desc': 'Twubaka abakobwa, abashinzwe kurera, n\'urubyiruko binyuze mu burezi, ubuzima, n\'ubumenyi kugira ngo twubake imiryango ifite icyizere.',
        'strategic.learn_more': 'Menya Byinshi',
        'strategic.impact_title': 'Impinduka zacu mu 2024',
        'strategic.stat1_label': 'Abagore n\'abakobwa \n bafashijwe',
        'strategic.stat2_label': 'Abakobwa bagumye mu ishuri \n binyuze mu bufasha bwacu',
        'strategic.stat3_label': 'Imishinga yatangiye \n kandi itera imbere',
        'strategic.stat4_label': 'Abashinzwe impinduka \n bahuguwe nka bahagaruzi',
        'strategic.title': 'Ingamba Zerekeza',
        'strategic.desc1': 'Ingamba zerekeza za LCEO zisobanura uko twumva impinduka, uko dutegura gahunda zacu, n\'uko tugera ku musaruro.',
        'strategic.desc2': 'Imirimo yacu ihuye n\'intego z\'igihugu n\'izisi kugira ngo tugere ku mpinduka ramba ku bakobwa n\'abagore bakiri bato.',
        'strategic.learn_more_btn': 'MENYA BYINSHI',
        'strategic.philosophy_title': 'Filozofiya Yacu',
        'strategic.philosophy_desc': 'LCEO yemera ko impinduka ramba itangirira mu mitekerereze, kwimenya, n\'icyizere cyo mu mutwe. Twibanda ku kubaka ubushobozi binyuze mu bikorwa byuzuye bikomeza icyizere, ubuzima bwo mu mutwe, uburyo bwo kwiga, n\'iterambere ry\'ubukungu. Ubu buryo bufasha abakobwa n\'abagore bakiri bato kwiga, kwigira mu bukungu, no kuvukamo abayobozi mu miryango yabo.',
        'strategic.change_model_badge': 'Modeli y\'Impinduka',
        'strategic.change_model_title': 'Impinduka mu Muryango Ihindura Imyanya y\'Igitsina',
        'strategic.change_model_desc': 'LCEO ishyira mu bikorwa imirimo yayo binyuze muri Modeli ya Rugero Rwiza (RR-CCM), uburyo buhindura imyanya y\'igitsina bugakemura imizi y\'ubusumbane mu nzego zose z\'umuryango.',
        'strategic.level1_title': '1. Urwego rw\'Umuntu ku Giti cye',
        'strategic.level1_desc': 'Kubaka ubushobozi, icyizere, n\'ubumenyi binyuze mu guhindura imitekerereze n\'uburyo bwo kwiga.',
        'strategic.level2_title': '2. Urwego rw\'Imibanire',
        'strategic.level2_desc': 'Guhindura imibanire binyuze mu guhuza abagabo n\'abahungu (Champions) n\'amatsinda y\'ubujyanama.',
        'strategic.level3_title': '3. Urwego rw\'Inzego',
        'strategic.level3_desc': 'Gukemura imbogamizi z\'inzego binyuze mu bufatanye n\'abayobozi b\'ibanze n\'ubuvugizi.',
        'strategic.alignment_title': 'Guhura n\'Intego z\'Igihugu n\'iz\'Isi',
        'strategic.vision2050_title': 'Icyerekezo 2050 (Vision 2050)',
        'strategic.vision2050_desc': 'Gufasha mu kubaka ubushobozi bw\'abantu, uburinganire, n\'iterambere ry\'ubukungu ry bose.',
        'strategic.nst2_title': 'NST2 Priorities',
        'strategic.nst2_desc': 'Bijyanye n\'uburezi bufite ireme, iterambere ry\'ubumenyi, n\'ubwirinzi bw\'imibereho myiza.',
        'strategic.econ_title': 'Ubukungu ryo bose',
        'strategic.econ_desc': 'Gufasha mu buryo buzuye mu ntego ya SDG 1 (Kunesha Ubukene) na SDG 8 (Umurimo Unoze).',
        'strategic.gender_title': 'Igitsina & Uburezi',
        'strategic.gender_desc': 'Gusohoza intego ya SDG 4 (Uburezi Bufite Ireme) na SDG 5 (Uburinganire) kugira ngo abakobwa bayobore.',
        'footer.address_value': 'Akarere ka Bugesera, Umurenge wa Nyamata, Intara y\'Iburasirazuba, Rwanda',
        'footer.phone_value': '+250 788 123 456',
        'footer.email_value': 'info.lceo@gmail.com',
        'footer.brand_name': 'Umuryango LCEO - Life-Changing Endeavor Organization.',
        'getinvolved.hero_title': 'Ba Umusemburo w\'Impinduka',
        'getinvolved.hero_desc': 'Hari uburyo bwinshi bwo gushyigikira intego za LCEO mu gushoboza abakobwa n\'abagore bafite ibibazo mu Rwanda. Hitamo uburyo bukwaniye bwo gukora impinduka.',
        'getinvolved.stats_banner': 'Buri gikorwa gifite agaciro. Fatanya n\'umuryango wacu w\'abaterankunga 5,000+ uyu munsi.',
        'getinvolved.badge': 'Gira Uruhare',
        'getinvolved.title': 'Uburyo bwo Gushyigikira Inshingano Zacu',
        'getinvolved.subtitle': 'Hitamo uburyo bukgufasha cyane',
        'getinvolved.impact_circle_title': 'Injira mu Itsinda ry\'Impinuka',
        'getinvolved.impact_circle_desc': 'Ba umuterankunga uhoraho utange ubufasha burambye buhindura ubuzima.',
        'getinvolved.impact_circle_cta': 'Tangira Gutanga buri Kwezi',
        'getinvolved.one_time_title': 'Tanga Inkunga y\'Inshuro Imwe',
        'getinvolved.one_time_desc': 'Buri nkunga, niyo yaba nto, ikora impinduka mu buzima bw\'abakobwa bari mu kaga.',
        'getinvolved.one_time_cta': 'Tanga Inkunga Ubu',
        'getinvolved.corporate_title': 'Ubufatanye n\'Ibigo',
        'getinvolved.corporate_desc': 'Fatanya na LCEO wagure ibikorwa byanyu byo gufasha sosiyete no gushoboza abato.',
        'getinvolved.corporate_cta': 'Shaka Ubufatanye',
        'getinvolved.volunteer_title': 'Tanga Umwanya wawe nk\'Uwitanga',
        'getinvolved.volunteer_desc': 'Sangiza ubumenyi n\'ubumenyingiro bwawe mu guhugura, kwigisha, cyangwa gushyigikira gahunda zacu.',
        'getinvolved.volunteer_cta': 'Saba kuba Uwitanga',
        'getinvolved.sponsor_title': 'Rera Umwana',
        'getinvolved.sponsor_desc': 'Shyigikira mu buryo butaziguye uburezi bw\'umukobwa, ubucuruzi bwe, cyangwa urugendo rwe rwo kwiteza imbere.',
        'getinvolved.sponsor_cta': 'Rera Umukobwa',
        'getinvolved.advocate_title': 'Kwaza Mission Yacu',
        'getinvolved.advocate_desc': 'Wagura inshingano zacu usangiza inkuru yacu ku mbuga nkoranyambaga no mu nshuti zawe.',
        'getinvolved.advocate_cta': 'Ba Umuvugizi',
        'getinvolved.monthly_impact_badge': 'Gutanga Buri Kwezi',
        'getinvolved.monthly_impact_title': 'Impinduka yawe ya buri Kwezi',
        'getinvolved.monthly_impact_desc': 'Reba uko inkunga yawe ihoraho ihindura ubuzima',
        'getinvolved.support_now_btn': 'SHYIGIKIRA UBU',
        'getinvolved.volunteer_with_us': 'Gira Uruhare nk\'Uwitanga',
        'getinvolved.volunteer_mission': 'Turashaka abantu bafite ishyaka ryo gusangiza ubumenyi bwabo no guhugura abayobozi b\'ejo hazaza.',
        'getinvolved.ready_title': 'Witeguye Gukora Impinduka?',
        'getinvolved.ready_desc': 'Fatanya n\'abaterankunga banyuranye bahindura ubuzima kandi bakubaka ejo hazaza heza ku bakobwa n\'abagore mu Rwanda.',
        'getinvolved.donate_now_btn': 'TANGA INKUNGA UBU',
        'getinvolved.contact_us_btn': 'TWANDIKIRE',
        'getinvolved.benefit_impact_updates': 'Amakuru agezweho ku bikorwa',
        'getinvolved.benefit_annual_reports': 'Raporo y\'umwaka ku mibereho y\'abafashwa',
        'getinvolved.benefit_exclusive_events': 'Gutumirwa mu birori byihariye',
        'getinvolved.benefit_tax_receipts': 'Inyemezabwishyu zemewe n\'imisoro',
        'getinvolved.benefit_choose_programs': 'Hitamo gahunda ushaka gushyigikira',
        'getinvolved.benefit_immediate_impact': 'Impinduka ihuse',
        'getinvolved.benefit_transparent_funds': 'Iterambere mu micungire y\'umutungo',
        'getinvolved.benefit_digital_receipt': 'Inyemezabwishyu mu buryo bw\'ikoranabuhanga',
        'getinvolved.benefit_co_branded': 'Ibikubiye mu bufatanye bw\'amazina y\'ibigo',
        'getinvolved.benefit_employee_engagement': 'Uburyo bwo guhuza abakozi k\'umushinga',
        'getinvolved.benefit_reporting': 'Gupima no gutanga raporo y\'impinduka',
        'getinvolved.benefit_visibility': 'Kumenyekanisha izina ry\'ikigo',
        'getinvolved.benefit_mentorship_ops': 'Uburyo bwo kuba umujyanama',
        'getinvolved.benefit_skills_volunteering': 'Ubwitange bushingiye k\'ubumenyi',
        'getinvolved.benefit_facilitation': 'Gufasha mu mahugurwa',
        'getinvolved.benefit_community_eng': 'Gusabana n\'abaturage',
        'getinvolved.benefit_personal_connection': 'Ivugana rya hafi n\'uwafashijwe',
        'getinvolved.benefit_progress_photos': 'Amakuru n\'amafoto y\'aho umushinga ugeze',
        'getinvolved.benefit_letter_exchange': 'Guhanahana amabaruwa',
        'getinvolved.benefit_lasting_impact': 'Impinduka irambye',
        'getinvolved.benefit_social_toolkit': 'Ibikoresho byo ku mbuga nkoranyambaga',
        'getinvolved.benefit_shareable_content': 'Ibikubiyemo bishobora gusangizwa abandi',
        'getinvolved.benefit_ambassador_prog': 'Gahunda y\'abambasaderi',
        'getinvolved.benefit_community_build': 'Kubaka umuryango',
        'getinvolved.impact_menstrual_kits': 'Bitanga ibikoresho by\'isuku ku bakobwa 5 mu gihe cy\'ukwezi',
        'getinvolved.impact_school_fees': 'Byishyura amashuri n\'ibikoresho k\'umukobwa umwe mu gihe cy\'izuba',
        'getinvolved.impact_seed_capital': 'Bitanga igishoro k\'umugore umwe w\'ihangamurimo',
        'getinvolved.impact_full_sponsor': 'Bishyura gahunda yose k\'umukobwa umwe ufashwa',
        'getinvolved.vol_mentorship': 'Ubuvugizi n\'Ubujyanama',
        'getinvolved.vol_training': 'Amahugurwa mu bucuruzi',
        'getinvolved.vol_education': 'Ubufasha mu burezi',
        'getinvolved.vol_outreach': 'Gushakira ubufasha mu muryango',
    },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
    const [language, setLanguage] = useState<Language>('en');

    const t = (key: string) => {
        return translations[language][key] || translations['en'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
