import {
    User,
    UserType,
    Language,
    StaffRole,
    BeneficiaryStatus,
    ProgramCategory,
    ProgramStatus,
    TrackingFrequency,
    GoalType,
    GoalStatus,
    DonationType,
    PaymentMethod,
    PaymentStatus,
    Currency,
    ReceiptPreference,
    NotificationType,
    NotificationStatus,
    NotificationChannel,
    MetricPeriod,
    MetricSource,
    AuthorRole,
    Program,
    Beneficiary,
    Donor,
    Donation,
    Story,
    ImpactMetric,
    WeeklyTracking,
    Goal,
    Staff,
    Project,
    RecurringDonation,
    RecurringFrequency,
    RecurringStatus,
    TaskStatus,
    AttendanceStatus
} from './types';

// Images
const IMAGES = {
    education: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=1080",
    entrepreneurship: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?q=80&w=1080",
    health: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?q=80&w=1080",
    portrait_1: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=1080",
    portrait_2: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=1080",
    portrait_3: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=1080",
    project_1: "https://images.unsplash.com/photo-1531206715517-5c0ba140b2b8?q=80&w=1080",
    project_2: "https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=1080",
};

// 1. Mock Users
export const mockUsers: User[] = [
    {
        id: 'u_admin',
        email: 'admin@lceo.org',
        fullName: 'Grace Administrator',
        phone: '+250780000001',
        userType: UserType.ADMIN,
        language: Language.EN,
        isVerified: true,
        verificationToken: null,
        verifiedAt: new Date('2023-01-01'),
        resetPasswordToken: null,
        resetPasswordExpires: null,
        offlineSyncToken: null,
        isActive: true,
        createdAt: new Date('2023-01-01'),
        updatedAt: new Date('2023-01-01'),
        lastLoginAt: new Date(),
    },
    {
        id: 'u_donor',
        email: 'donor@lceo.org',
        fullName: 'Robert Donor',
        phone: '+15550000002',
        userType: UserType.DONOR,
        language: Language.EN,
        isVerified: true,
        verificationToken: null,
        verifiedAt: new Date('2023-02-15'),
        resetPasswordToken: null,
        resetPasswordExpires: null,
        offlineSyncToken: null,
        isActive: true,
        createdAt: new Date('2023-02-15'),
        updatedAt: new Date('2023-02-15'),
        lastLoginAt: new Date(),
    },
    {
        id: 'u_ben1',
        email: 'ben@lceo.org',
        fullName: 'Ineza Keza',
        phone: '+250781234567',
        userType: UserType.BENEFICIARY,
        language: Language.RW,
        isVerified: true,
        verificationToken: null,
        verifiedAt: new Date('2023-03-10'),
        resetPasswordToken: null,
        resetPasswordExpires: null,
        offlineSyncToken: null,
        isActive: true,
        createdAt: new Date('2023-03-10'),
        updatedAt: new Date('2023-03-10'),
        lastLoginAt: null,
    },
    {
        id: 'u_ben2',
        email: 'ben2@lceo.org',
        fullName: 'Aline Uwase',
        phone: '+250781234568',
        userType: UserType.BENEFICIARY,
        language: Language.RW,
        isVerified: true,
        verificationToken: null,
        verifiedAt: new Date('2023-04-10'),
        resetPasswordToken: null,
        resetPasswordExpires: null,
        offlineSyncToken: null,
        isActive: true,
        createdAt: new Date('2023-04-10'),
        updatedAt: new Date('2023-04-10'),
        lastLoginAt: null,
    },
    {
        id: 'u_staff',
        email: 'staff@lceo.org',
        fullName: 'Jean Staff',
        phone: '+250780000003',
        userType: UserType.ADMIN, // Staff are admins in UserType usually, but distinguished in Staff entity
        language: Language.EN,
        isVerified: true,
        verificationToken: null,
        verifiedAt: new Date('2023-01-15'),
        resetPasswordToken: null,
        resetPasswordExpires: null,
        offlineSyncToken: null,
        isActive: true,
        createdAt: new Date('2023-01-15'),
        updatedAt: new Date('2023-01-15'),
        lastLoginAt: new Date(),
    },
];

// 2. Mock Staff
export const mockStaff: Staff[] = [
    {
        id: 's1',
        user: mockUsers[0],
        fullName: 'Grace Administrator',
        role: StaffRole.SUPER_ADMIN,
        department: 'Executive',
        permissions: ['all'],
        employeeId: 'EMP001',
        hireDate: new Date('2022-01-01'),
        contactInfo: {
            emergencyContact: 'John Doe',
            emergencyPhone: '+250780000001',
            address: 'Kigali, Rwanda',
        },
        isActive: true,
        createdAt: new Date('2022-01-01'),
        updatedAt: new Date('2022-01-01'),
        submittedTrackings: [],
        verifiedTrackings: [],
        uploadedDocuments: [],
        verifiedDocuments: [],
        verifiedMetrics: [],
    },
    {
        id: 's2',
        user: mockUsers[4],
        fullName: 'Jean Staff',
        role: StaffRole.PROGRAM_MANAGER,
        department: 'Programs',
        permissions: ['manage_programs', 'view_beneficiaries'],
        employeeId: 'EMP002',
        hireDate: new Date('2023-01-20'),
        contactInfo: {
            emergencyContact: 'Jane Doe',
            emergencyPhone: '+250780000004',
            address: 'Kigali, Rwanda',
        },
        isActive: true,
        createdAt: new Date('2023-01-20'),
        updatedAt: new Date('2023-01-20'),
        submittedTrackings: [],
        verifiedTrackings: [],
        uploadedDocuments: [],
        verifiedDocuments: [],
        verifiedMetrics: [],
    }
];

// 3. Mock Programs
export const mockPrograms: Program[] = [
    {
        id: 'p1',
        name: { en: 'She Can Code', rw: 'Abakobwa Mu Ikoranabuhanga' },
        description: {
            en: 'Empowering young women with software development skills to bridge the gender gap in tech.',
            rw: 'Gufasha abakobwa kwiga gukora porogaramu za mudasobwa kugirango bagabanye icyuho cy\'uburinganire mu ikoranabuhanga.'
        },
        category: ProgramCategory.EDUCATION,
        sdgAlignment: [4, 5, 8],
        kpiTargets: { graduates: 100, employed: 80 },
        startDate: new Date('2023-01-01'),
        endDate: null,
        status: ProgramStatus.ACTIVE,
        budget: 50000,
        fundsAllocated: 30000,
        fundsUtilized: 15000,
        coverImage: IMAGES.education,
        logo: null,
        sortOrder: 1,
        metadata: null,
        createdAt: new Date('2022-12-01'),
        updatedAt: new Date('2023-01-01'),
        projects: [],
        beneficiaries: [],
        impactMetrics: [],
        stories: [],
        donations: [],
    },
    {
        id: 'p2',
        name: { en: 'Business Incubation', rw: 'Inzozi Nziza' },
        description: {
            en: 'Supporting women entrepreneurs to start and grow businesses through seed funding and mentorship.',
            rw: 'Gufasha ba rwiyemezamirimo b\'abagore gutangira no guteza imbere ubucuruzi binyuze mu gutera inkunga no guhugurwa.'
        },
        category: ProgramCategory.ENTREPRENEURSHIP,
        sdgAlignment: [1, 5, 8],
        kpiTargets: { businessesStarted: 50, revenueIncrease: 20 },
        startDate: new Date('2023-02-01'),
        endDate: null,
        status: ProgramStatus.ACTIVE,
        budget: 75000,
        fundsAllocated: 50000,
        fundsUtilized: 20000,
        coverImage: IMAGES.entrepreneurship,
        logo: null,
        sortOrder: 2,
        metadata: null,
        createdAt: new Date('2023-01-15'),
        updatedAt: new Date('2023-02-01'),
        projects: [],
        beneficiaries: [],
        impactMetrics: [],
        stories: [],
        donations: [],
    },
    {
        id: 'p3',
        name: { en: 'Community Health', rw: 'Ubuzima Bwiza' },
        description: {
            en: 'Providing health education, reproductive health resources, and hygiene kits to rural communities.',
            rw: 'Gutanga inyigisho z\'ubuzima, ibikoresho by\'ubuzima bw\'imyororokere, n\'ibikoresho by\'isuku mu baturage.'
        },
        category: ProgramCategory.HEALTH,
        sdgAlignment: [3, 5],
        kpiTargets: { peopleReached: 1000, screenings: 500 },
        startDate: new Date('2023-03-01'),
        endDate: null,
        status: ProgramStatus.ACTIVE,
        budget: 25000,
        fundsAllocated: 25000,
        fundsUtilized: 10000,
        coverImage: IMAGES.health,
        logo: null,
        sortOrder: 3,
        metadata: null,
        createdAt: new Date('2023-02-15'),
        updatedAt: new Date('2023-03-01'),
        projects: [],
        beneficiaries: [],
        impactMetrics: [],
        stories: [],
        donations: [],
    }
];

// 4. Mock Projects
export const mockProjects: Project[] = [
    {
        id: 'proj1',
        program: mockPrograms[0],
        name: { en: 'Bootcamp Cohort 1', rw: 'Icyiciro cya 1' },
        description: { en: 'First cohort of 30 students', rw: 'Icyiciro cya mbere cy\'abanyeshuri 30' },
        budgetRequired: 15000,
        budgetReceived: 15000,
        budgetUtilized: 14000,
        timeline: { start: new Date('2023-01-01'), end: new Date('2023-06-01'), milestones: [] },
        location: { districts: ['Gasabo'], sectors: ['Kacyiru'] },
        impactMetrics: { beneficiariesTarget: 30, beneficiariesReached: 28, successIndicators: [] },
        donationAllocationPercentage: 100,
        isActive: true,
        isFeatured: false,
        coverImage: IMAGES.project_1,
        gallery: [],
        createdAt: new Date('2023-01-01'),
        updatedAt: new Date('2023-01-01'),
        donations: []
    }
];


// 5. Mock Beneficiaries
export const mockBeneficiaries: Beneficiary[] = [
    {
        id: 'b1',
        user: mockUsers[2],
        fullName: 'Ineza Keza',
        dateOfBirth: new Date('2000-05-15'),
        location: { district: 'Gasabo', sector: 'Kacyiru', cell: 'Kamatamu', village: 'Village A' },
        program: mockPrograms[1],
        status: BeneficiaryStatus.ACTIVE,
        enrollmentDate: new Date('2023-03-10'),
        exitDate: null,
        startCapital: 50000,
        currentCapital: 75000,
        businessType: 'Retail Shop',
        trackingFrequency: TrackingFrequency.WEEKLY,
        lastTrackingDate: new Date(),
        nextTrackingDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
        profileCompletion: 85,
        requiresSpecialAttention: false,
        createdAt: new Date('2023-03-10'),
        updatedAt: new Date('2023-03-10'),
        weeklyTrackings: [],
        goals: [],
        documents: [],
        emergencyContacts: [],
    },
    {
        id: 'b2',
        user: mockUsers[3],
        fullName: 'Aline Uwase',
        dateOfBirth: new Date('1999-08-20'),
        location: { district: 'Nyarugenge', sector: 'Nyamirambo', cell: 'Rwezamenyo', village: 'Village B' },
        program: mockPrograms[0],
        status: BeneficiaryStatus.GRADUATED,
        enrollmentDate: new Date('2023-01-10'),
        exitDate: new Date('2023-07-10'),
        startCapital: 0,
        currentCapital: 0,
        businessType: 'Software Developer',
        trackingFrequency: TrackingFrequency.MONTHLY,
        lastTrackingDate: new Date('2023-07-01'),
        nextTrackingDate: null,
        profileCompletion: 100,
        requiresSpecialAttention: false,
        createdAt: new Date('2023-01-10'),
        updatedAt: new Date('2023-07-10'),
        weeklyTrackings: [],
        goals: [],
        documents: [],
        emergencyContacts: [],
    }
];

// 6. Mock Donors
export const mockDonors: Donor[] = [
    {
        id: 'd1',
        user: mockUsers[1],
        fullName: 'Robert Donor',
        country: 'USA',
        preferredCurrency: Currency.USD,
        communicationPreferences: { email: true, sms: false },
        receiptPreference: ReceiptPreference.EMAIL,
        totalDonated: 1500,
        lastDonationDate: new Date('2023-09-15'),
        isRecurringDonor: true,
        anonymityPreference: false,
        receiveNewsletter: true,
        createdAt: new Date('2023-02-15'),
        updatedAt: new Date('2023-09-15'),
        donations: [],
        recurringDonations: [],
    }
];

// 7. Mock Donations
export const mockDonations: Donation[] = [
    {
        id: 'don1',
        donor: mockDonors[0],
        amount: 500,
        currency: 'USD',
        localAmount: 650000,
        exchangeRate: 1300,
        donationType: DonationType.ONE_TIME,
        project: mockProjects[0],
        program: mockPrograms[0],
        paymentMethod: PaymentMethod.CARD,
        paymentStatus: PaymentStatus.COMPLETED,
        transactionId: 'TXN123456',
        paymentDetails: null,
        receiptSent: true,
        receiptSentAt: new Date('2023-09-15'),
        receiptNumber: 'RCPT-001',
        isAnonymous: false,
        metadata: null,
        donorMessage: "Keep up the great work!",
        isTest: false,
        createdAt: new Date('2023-09-15'),
        updatedAt: new Date('2023-09-15'),
    },
    {
        id: 'don2',
        donor: mockDonors[0],
        amount: 100,
        currency: 'USD',
        localAmount: 130000,
        exchangeRate: 1300,
        donationType: DonationType.MONTHLY,
        project: null,
        program: mockPrograms[1],
        paymentMethod: PaymentMethod.CARD,
        paymentStatus: PaymentStatus.COMPLETED,
        transactionId: 'TXN789012',
        paymentDetails: null,
        receiptSent: true,
        receiptSentAt: new Date('2023-10-01'),
        receiptNumber: 'RCPT-002',
        isAnonymous: false,
        metadata: null,
        donorMessage: null,
        isTest: false,
        createdAt: new Date('2023-10-01'),
        updatedAt: new Date('2023-10-01'),
    }
];

mockDonors[0].donations = mockDonations;


// 8. Mock Stories
export const mockStories: Story[] = [
    {
        id: 'st1',
        title: { en: 'From Struggle to Success: Ineza\'s Journey', rw: 'Urugendo rwa Ineza: Kuva mu buzima bugoye kugera ku ntsinzi' },
        content: {
            en: 'Ineza started her small business with just 50,000 RWF. Through the Business Incubation program, she learned how to manage her finances and grow her customer base. Today, she employs two other women from her village.',
            rw: 'Ineza yatangiranye igishoro cya 50,000 RWF. Binyuze muri porogaramu ya Inzozi Nziza, yize gucunga imari ye no kongera abakiriya. Ubu afite abakozi babiri.'
        },
        authorName: 'LCEO Comms',
        authorRole: AuthorRole.STAFF,
        authorPhoto: null,
        program: mockPrograms[1],
        beneficiaryId: 'b1',
        media: [
            { url: IMAGES.portrait_1, type: 'image', caption: 'Ineza at her shop', thumbnail: IMAGES.portrait_1 }
        ],
        isFeatured: true,
        isPublished: true,
        publishedDate: new Date('2023-09-01'),
        language: Language.EN,
        viewCount: 120,
        shareCount: 15,
        metadata: { tags: ['success', 'entrepreneurship'], location: 'Kigali', duration: 0 },
        createdAt: new Date('2023-09-01'),
        updatedAt: new Date('2023-09-01'),
    },
    {
        id: 'st2',
        title: { en: 'Graduation Day for Coding Class', rw: 'Umunsi wo gusoza amasomo ya Coding' },
        content: {
            en: '50 young women graduated from our She Can Code program last week. They are now ready to join the tech workforce.',
            rw: 'Abakobwa 50 basoje amasomo yabo muri She Can Code mu cyumweru gishize. Ubu biteguye kwinjira ku isoko ry\'umurimo.'
        },
        authorName: 'LCEO Comms',
        authorRole: AuthorRole.STAFF,
        authorPhoto: null,
        program: mockPrograms[0],
        beneficiaryId: null,
        media: [
            { url: IMAGES.education, type: 'image', caption: 'Graduation Ceremony', thumbnail: IMAGES.education }
        ],
        isFeatured: true,
        isPublished: true,
        publishedDate: new Date('2023-10-15'),
        language: Language.EN,
        viewCount: 200,
        shareCount: 45,
        metadata: { tags: ['education', 'tech'], location: 'Kigali', duration: 0 },
        createdAt: new Date('2023-10-15'),
        updatedAt: new Date('2023-10-15'),
    }
];

// 9. Mock Impact Metrics
export const mockImpactMetrics: ImpactMetric[] = [
    {
        id: 'im1',
        program: mockPrograms[0],
        metricName: 'Graduates Employed',
        metricValue: 45,
        measurementUnit: 'Count',
        period: MetricPeriod.QUARTERLY,
        periodDate: new Date('2023-09-30'),
        source: MetricSource.SYSTEM_CALCULATED,
        notes: null,
        verifiedBy: mockStaff[0],
        verifiedAt: new Date('2023-10-05'),
        createdAt: new Date('2023-10-05'),
    },
    {
        id: 'im2',
        program: mockPrograms[1],
        metricName: 'Total Capital Growth',
        metricValue: 1500000,
        measurementUnit: 'RWF',
        period: MetricPeriod.MONTHLY,
        periodDate: new Date('2023-09-30'),
        source: MetricSource.MANUAL,
        notes: 'Aggregated from weekly tracking',
        verifiedBy: mockStaff[0],
        verifiedAt: new Date('2023-10-02'),
        createdAt: new Date('2023-10-02'),
    }
];

// 10. Mock Weekly Tracking (for dashboards)
export const mockTrackings: WeeklyTracking[] = [
    {
        id: 'wt1',
        beneficiary: mockBeneficiaries[0],
        weekEnding: new Date('2023-10-20'),
        attendance: AttendanceStatus.PRESENT,
        taskGiven: 'Record daily sales',
        taskCompletionStatus: TaskStatus.COMPLETED,
        incomeThisWeek: 50000,
        expensesThisWeek: 20000,
        currentCapital: 80000,
        salesData: { unitsSold: 50, averagePrice: 1000, bestSellingProduct: 'Rice' },
        challenges: null,
        solutionsImplemented: null,
        notes: 'Good progress',
        nextWeekPlan: { tasks: ['Buy new stock'], goals: ['Increase sales by 10%'], supportNeeded: [] },
        submittedBy: mockBeneficiaries[0].user,
        submittedByType: UserType.BENEFICIARY,
        isOfflineSync: false,
        syncSessionId: null,
        offlineData: null,
        submittedAt: new Date('2023-10-20'),
        verifiedAt: new Date('2023-10-21'),
        verifiedBy: mockStaff[0]
    }
];
mockBeneficiaries[0].weeklyTrackings = mockTrackings;

// Helper to get stats
export const getDashboardStats = () => {
    return {
        totalBeneficiaries: 150,
        activeBeneficiaries: 120,
        graduatedBeneficiaries: 30,
        totalDonors: 45,
        totalDonations: 25000,
        activePrograms: 3,
        growthRate: 8.2,
        trends: {
            donationsGrowth: 12.5,
            beneficiariesGrowth: 8.2,
            graduatedGrowth: 15.3,
            growthRateTrend: 2.1
        },
        programDistribution: [
            { name: 'Education', value: 127, color: '#17d1ac' },
            { name: 'Entrepreneurship', value: 85, color: '#d2b48c' },
            { name: 'Health', value: 175, color: '#122f2b' },
            { name: 'Cross-Cutting', value: 45, color: '#ff4757' },
        ],
        recentDonations: mockDonations,
        monthlyTrends: [
            { month: 'Jan', beneficiaries: 30, donations: 1500 },
            { month: 'Feb', beneficiaries: 50, donations: 2500 },
            { month: 'Mar', beneficiaries: 70, donations: 3500 },
            { month: 'Apr', beneficiaries: 90, donations: 4500 },
            { month: 'May', beneficiaries: 110, donations: 5500 },
            { month: 'Jun', beneficiaries: 120, donations: 6000 },
        ]
    };
};
